"""荷兰语的练习清单:整句 + 搭配。

比英语那套刻意更简单。英语是"读得懂但说不地道"的问题,所以要练话语框架和
词块;荷兰语是零基础起步,这个阶段**能把一句话整句说出来**比什么都重要,
所以不做话语框架,只有两类:

* **整句**——在荷兰真实会遇到的场合里,原样能用的一句话。点菜、问路、
  听不懂请对方再说一遍。
* **搭配**——动词和它常跟的名词,以及日常动作。荷兰语的难点在于动词往往
  跑到句尾、而且很多说法与英语不对应(``boodschappen doen`` 不是 do shopping)。

干扰项是中文直译或照英语套过来的版本——后者尤其常见:会英语的人学荷兰语,
第一反应就是把英语逐词换过去。
"""

from __future__ import annotations

from src.growth.catalog import Pattern, build_catalog

_PHRASE_GROUPS = {
    "A": "打招呼与客套",
    "B": "点餐与购物",
    "C": "问路与出行",
    "D": "听不懂与求助",
    "E": "约时间与安排",
    "F": "表态与回应",
}

_SCENE_GROUPS = {
    "A": "日常起居",
    "B": "出行与办事",
    "C": "工作与学习",
    "D": "手上的动作",
}

#: (id, 荷兰语, 分组, 难度, 释义, 情境, 例句)
_RAW_PHRASES: tuple[tuple, ...] = (
    # ── A 打招呼与客套 ────────────────────────────────────────────────────────
    ("nl-goedemorgen", "Goedemorgen.", "A", "core", "早上好",
     "你上午进店或进办公室,先打个招呼。",
     ("Goedemorgen! Alles goed?", "Goedemorgen, meneer.")),
    ("nl-hoe-gaat-het", "Hoe gaat het?", "A", "core", "你好吗?(最常用的寒暄)",
     "碰到熟人,你要问一句近况。",
     ("Hé, hoe gaat het?", "Hoe gaat het met je?")),
    ("nl-goed-en-met-jou", "Goed, en met jou?", "A", "core", "挺好的,你呢?",
     "对方问你好不好,你答完要把问题递回去。",
     ("\"Hoe gaat het?\" \"Goed, en met jou?\"", "Prima, en met jou?")),
    ("nl-alsjeblieft", "Alsjeblieft.", "A", "core", "给你 / 请(递东西或提请求时)",
     "你把东西递给对方。",
     ("Hier, alsjeblieft.", "Mag ik de rekening, alsjeblieft?")),
    ("nl-dank-je-wel", "Dank je wel.", "A", "core", "谢谢(对熟人)",
     "别人帮了你一个小忙。",
     ("Dank je wel voor je hulp.", "Dank u wel, meneer.")),
    ("nl-graag-gedaan", "Graag gedaan.", "A", "core", "不客气",
     "对方向你道谢,你回一句。",
     ("\"Dank je wel!\" \"Graag gedaan.\"", "Geen dank, graag gedaan.")),
    ("nl-tot-ziens", "Tot ziens.", "A", "core", "再见(正式一点)",
     "你离开店里或结束一次正式会面。",
     ("Tot ziens, fijne dag!", "Tot ziens en bedankt.")),
    ("nl-tot-morgen", "Tot morgen.", "A", "core", "明天见",
     "下班时跟同事告别。",
     ("Tot morgen!", "Oké, tot morgen dan.")),
    ("nl-fijne-dag", "Fijne dag nog!", "A", "mid", "祝你今天愉快",
     "结账或道别时加一句客套。",
     ("Bedankt, fijne dag nog!", "Fijn weekend nog!")),
    ("nl-sorry", "Sorry, hoor.", "A", "mid", "不好意思(轻微致歉,很口语)",
     "你不小心挡了别人的路。",
     ("Sorry hoor, ik zag je niet.", "Sorry, dat was mijn fout.")),

    # ── B 点餐与购物 ──────────────────────────────────────────────────────────
    ("nl-mag-ik", "Mag ik …?", "B", "core", "我可以要……吗?(点东西最常用)",
     "你在咖啡店要点一杯咖啡。",
     ("Mag ik een koffie, alsjeblieft?", "Mag ik even kijken?")),
    ("nl-ik-wil-graag", "Ik wil graag …", "B", "core", "我想要……",
     "你在柜台说明你要什么。",
     ("Ik wil graag twee broodjes.", "Ik wil graag betalen.")),
    ("nl-wat-kost-dit", "Wat kost dit?", "B", "core", "这个多少钱?",
     "你拿着一样东西问价钱。",
     ("Wat kost dit?", "Wat kosten deze?")),
    ("nl-de-rekening", "De rekening, alsjeblieft.", "B", "core", "请结账",
     "吃完饭你要买单。",
     ("Mag ik de rekening, alsjeblieft?", "De rekening graag.")),
    ("nl-pinnen", "Kan ik pinnen?", "B", "core", "可以刷卡吗?(荷兰最常用的支付问法)",
     "你要确认这家店能不能刷卡。",
     ("Kan ik hier pinnen?", "Pinnen mag altijd.")),
    ("nl-een-moment", "Een moment, alstublieft.", "B", "mid", "请稍等一下",
     "你需要对方等几秒钟。",
     ("Een moment, ik pak het even.", "Momentje!")),
    ("nl-is-dat-alles", "Is dat alles?", "B", "mid", "就这些吗?",
     "店员问你还要不要别的。",
     ("\"Is dat alles?\" \"Ja, dat is alles.\"", "Verder nog iets?")),
    ("nl-ik-kijk-even", "Ik kijk even rond.", "B", "mid", "我先随便看看",
     "店员来问要不要帮忙,你只是想逛逛。",
     ("Dank je, ik kijk even rond.", "Ik kijk alleen even.")),

    # ── C 问路与出行 ──────────────────────────────────────────────────────────
    ("nl-waar-is", "Waar is …?", "C", "core", "……在哪里?",
     "你要问洗手间在哪。",
     ("Waar is het station?", "Waar is de wc?")),
    ("nl-hoe-kom-ik", "Hoe kom ik bij …?", "C", "core", "我怎么去……?",
     "你要问去中央车站怎么走。",
     ("Hoe kom ik bij het centraal station?", "Hoe kom ik daar het snelst?")),
    ("nl-rechtdoor", "Rechtdoor en dan links.", "C", "core", "直走然后左转",
     "你要给别人指路。",
     ("Rechtdoor en dan rechts.", "Ga rechtdoor tot het kruispunt.")),
    ("nl-hoe-ver", "Hoe ver is het?", "C", "core", "还有多远?",
     "你想知道还要走多久。",
     ("Hoe ver is het lopen?", "Is het ver hiervandaan?")),
    ("nl-welk-spoor", "Welk spoor?", "C", "mid", "几号站台?",
     "你在火车站要确认站台。",
     ("Welk spoor is het?", "Spoor vijf, geloof ik.")),
    ("nl-hoe-laat", "Hoe laat vertrekt de trein?", "C", "mid", "火车几点开?",
     "你要确认发车时间。",
     ("Hoe laat vertrekt de trein?", "Hoe laat begint het?")),
    ("nl-ik-ben-verdwaald", "Ik ben verdwaald.", "C", "mid", "我迷路了",
     "你找不到方向,得向人求助。",
     ("Sorry, ik ben verdwaald.", "We zijn een beetje verdwaald.")),

    # ── D 听不懂与求助 ────────────────────────────────────────────────────────
    ("nl-kun-je-herhalen", "Kun je dat herhalen?", "D", "core", "能再说一遍吗?",
     "对方说太快你没听清。",
     ("Sorry, kun je dat herhalen?", "Kunt u dat herhalen, alstublieft?")),
    ("nl-langzamer", "Kun je wat langzamer praten?", "D", "core", "能说慢一点吗?",
     "你跟得上单词但跟不上语速。",
     ("Sorry, kun je wat langzamer praten?", "Iets langzamer, alsjeblieft.")),
    ("nl-ik-begrijp-het-niet", "Ik begrijp het niet.", "D", "core", "我没听懂",
     "你完全没理解对方的意思。",
     ("Sorry, ik begrijp het niet.", "Ik begrijp het nu wel.")),
    ("nl-wat-betekent", "Wat betekent dat?", "D", "core", "那是什么意思?",
     "你听到一个不认识的词。",
     ("Wat betekent dat woord?", "Wat betekent \"gezellig\"?")),
    ("nl-spreekt-u-engels", "Spreekt u Engels?", "D", "core", "您会说英语吗?",
     "你实在说不下去了,要换语言。",
     ("Sorry, spreekt u Engels?", "Spreek je Engels?")),
    ("nl-ik-leer-nog", "Ik leer het nog.", "D", "mid", "我还在学(所以说得慢)",
     "你要说明自己是初学者。",
     ("Sorry, ik leer het nog.", "Mijn Nederlands is nog niet zo goed.")),
    ("nl-hoe-zeg-je", "Hoe zeg je dat in het Nederlands?", "D", "mid", "这个荷兰语怎么说?",
     "你想问一个词的荷兰语说法。",
     ("Hoe zeg je dat in het Nederlands?", "Hoe schrijf je dat?")),
    ("nl-kun-je-me-helpen", "Kun je me helpen?", "D", "core", "你能帮我一下吗?",
     "你需要别人搭把手。",
     ("Kun je me even helpen?", "Kunt u mij helpen, alstublieft?")),

    # ── E 约时间与安排 ────────────────────────────────────────────────────────
    ("nl-zullen-we", "Zullen we …?", "E", "core", "我们要不要……?(提议)",
     "你想约对方一起去喝一杯。",
     ("Zullen we koffie drinken?", "Zullen we gaan?")),
    ("nl-heb-je-tijd", "Heb je tijd?", "E", "core", "你有空吗?",
     "你想约对方见面。",
     ("Heb je morgen tijd?", "Heb je even tijd?")),
    ("nl-het-komt-niet-uit", "Het komt me niet uit.", "E", "mid", "这个时间我不方便",
     "对方提的时间你去不了。",
     ("Sorry, het komt me niet uit.", "Vrijdag komt me beter uit.")),
    ("nl-tot-dan", "Tot dan!", "E", "core", "到时候见",
     "约好了时间,你收尾一句。",
     ("Oké, tot dan!", "Prima, tot dan.")),
    ("nl-ik-ben-wat-later", "Ik ben wat later.", "E", "mid", "我会晚一点到",
     "你在路上要通知对方。",
     ("Sorry, ik ben wat later.", "Ik ben tien minuten later.")),

    # ── F 表态与回应 ──────────────────────────────────────────────────────────
    ("nl-dat-klopt", "Dat klopt.", "F", "core", "没错 / 是这样",
     "对方说的信息是对的,你确认一句。",
     ("\"Je woont in Amsterdam?\" \"Dat klopt.\"", "Dat klopt niet.")),
    ("nl-geen-probleem", "Geen probleem.", "F", "core", "没问题 / 没事",
     "对方为一件小事道歉。",
     ("\"Sorry!\" \"Geen probleem.\"", "Dat is geen probleem.")),
    ("nl-prima", "Prima!", "F", "core", "挺好 / 可以(爽快同意)",
     "对方提了个安排,你答应。",
     ("\"Zullen we om zeven uur?\" \"Prima!\"", "Dat is prima.")),
    ("nl-ik-weet-het-niet", "Ik weet het niet.", "F", "core", "我不知道",
     "被问到你答不上来的事。",
     ("Sorry, ik weet het niet.", "Ik weet het echt niet.")),
    ("nl-misschien", "Misschien.", "F", "core", "也许吧(不把话说死)",
     "你还不确定去不去。",
     ("Misschien, ik laat het weten.", "Misschien morgen.")),
    ("nl-dat-hangt-ervan-af", "Dat hangt ervan af.", "F", "mid", "那要看情况",
     "答案取决于别的条件。",
     ("Dat hangt ervan af hoe laat het is.", "Dat hangt van het weer af.")),
    ("nl-ik-denk-het-wel", "Ik denk het wel.", "F", "mid", "我觉得应该是",
     "你比较确定但不绝对。",
     ("\"Komt hij ook?\" \"Ik denk het wel.\"", "Ik denk het niet.")),
    ("nl-wat-jammer", "Wat jammer!", "F", "mid", "太可惜了",
     "对方说了一件遗憾的事。",
     ("Wat jammer dat je niet kunt.", "Jammer, volgende keer dan.")),
    ("nl-gezellig", "Gezellig!", "F", "mid", "真惬意 / 气氛真好(荷兰语的招牌词)",
     "你和朋友坐下来喝酒聊天,气氛很好。",
     ("Wat gezellig!", "Het was heel gezellig, bedankt.")),
    ("nl-doe-maar", "Doe maar.", "F", "mid", "那就这样吧 / 来一个吧",
     "店员问要不要加一份,你同意。",
     ("\"Nog een biertje?\" \"Doe maar.\"", "Doe maar twee.")),
    ("nl-laat-maar", "Laat maar.", "F", "mid", "算了,不用了",
     "你本来要说的事不重要了。",
     ("Laat maar, het is niet belangrijk.", "Laat maar zitten.")),
    ("nl-het-geeft-niet", "Het geeft niet.", "F", "mid", "没关系(安慰对方)",
     "对方因为一件小事很过意不去。",
     ("\"Sorry, ik was het vergeten.\" \"Het geeft niet.\"", "Geeft niks hoor.")),
)

#: (id, 荷兰语, 分组, 难度, 释义, 情境, 例句, 错误版)
_RAW_COLLOCATIONS: tuple[tuple, ...] = (
    # ── A 日常起居 ────────────────────────────────────────────────────────────
    ("nlc-boodschappen-doen", "boodschappen doen", "A", "core", "买菜 / 采购日用品",
     "你要说下班后得去超市。",
     ("Ik moet nog boodschappen doen.", "Zullen we samen boodschappen doen?"),
     ("inkopen maken", "winkelen doen")),
    ("nlc-koffie-zetten", "koffie zetten", "A", "core", "煮咖啡",
     "你要问对方要不要煮壶咖啡。",
     ("Zal ik koffie zetten?", "Hij zet elke ochtend koffie."),
     ("koffie maken", "koffie koken")),
    ("nlc-afwassen", "de afwas doen", "A", "core", "洗碗",
     "你说饭后由你收拾。",
     ("Ik doe de afwas wel.", "Wie doet vandaag de afwas?"),
     ("de borden wassen", "schotels schoonmaken")),
    ("nlc-de-was-doen", "de was doen", "A", "core", "洗衣服",
     "你说这周末得洗衣服。",
     ("Ik moet de was nog doen.", "De was hangt buiten."),
     ("kleren wassen maken", "wasgoed doen")),
    ("nlc-opruimen", "opruimen", "A", "core", "收拾 / 整理",
     "你要说把桌子收拾一下。",
     ("Kun je even opruimen?", "Ik heb de kamer opgeruimd."),
     ("schoon maken alles", "orde maken")),
    ("nlc-het-licht-aandoen", "het licht aandoen", "A", "core", "开灯",
     "屋里太暗,你让人开灯。",
     ("Doe het licht even aan.", "Vergeet niet het licht uit te doen."),
     ("het licht openen", "de lamp open maken")),
    ("nlc-de-deur-dichtdoen", "de deur dichtdoen", "A", "core", "关门",
     "你让对方把门带上。",
     ("Doe de deur even dicht.", "De deur staat open."),
     ("de deur sluiten maken", "de deur close doen")),
    ("nlc-slapen-gaan", "naar bed gaan", "A", "core", "去睡觉",
     "你说你要去睡了。",
     ("Ik ga naar bed.", "Hij gaat altijd laat naar bed."),
     ("gaan slapen bed", "naar slaap gaan")),

    # ── B 出行与办事 ──────────────────────────────────────────────────────────
    ("nlc-de-trein-nemen", "de trein nemen", "B", "core", "坐火车",
     "你要说你坐火车去。",
     ("Ik neem de trein naar Utrecht.", "Neem je de trein of de bus?"),
     ("de trein zitten", "met trein gaan nemen")),
    ("nlc-fietsen", "op de fiets gaan", "B", "core", "骑车去",
     "你说骑自行车过去更快。",
     ("Ik ga op de fiets.", "Zullen we op de fiets gaan?"),
     ("fiets rijden gaan", "met fiets zitten")),
    ("nlc-een-afspraak-maken", "een afspraak maken", "B", "core", "约个时间 / 预约",
     "你要跟医生约时间。",
     ("Ik wil een afspraak maken.", "We hebben een afspraak om drie uur."),
     ("een afspraak doen", "tijd maken met")),
    ("nlc-geld-pinnen", "geld pinnen", "B", "mid", "取现金",
     "你要先去取点钱。",
     ("Ik moet even geld pinnen.", "Kun je hier geld pinnen?"),
     ("geld nemen uit", "cash halen")),
    ("nlc-een-formulier-invullen", "een formulier invullen", "B", "mid", "填表",
     "办事时要填一张表格。",
     ("Je moet dit formulier invullen.", "Heb je het formulier al ingevuld?"),
     ("een formulier schrijven", "het formulier vol maken")),
    ("nlc-huur-betalen", "de huur betalen", "B", "mid", "交房租",
     "你要说月初要交房租。",
     ("De huur moet voor de eerste betaald zijn.", "Ik heb de huur al betaald."),
     ("huis geld geven", "de huur doen")),

    # ── C 工作与学习 ──────────────────────────────────────────────────────────
    ("nlc-een-vraag-stellen", "een vraag stellen", "C", "core", "提问",
     "你要在课上问一个问题。",
     ("Mag ik een vraag stellen?", "Hij stelde een goede vraag."),
     ("een vraag vragen", "een vraag maken")),
    ("nlc-aandacht-besteden", "aandacht besteden aan", "C", "mid", "注意 / 留心",
     "你要提醒对方留意细节。",
     ("Besteed aandacht aan de details.", "Hij besteedt er geen aandacht aan."),
     ("aandacht geven op", "attentie betalen")),
    ("nlc-een-fout-maken", "een fout maken", "C", "core", "犯错",
     "你要承认自己弄错了。",
     ("Ik heb een fout gemaakt.", "Iedereen maakt fouten."),
     ("een fout doen", "verkeerd maken")),
    ("nlc-afspraak-nakomen", "een afspraak nakomen", "C", "high", "守约 / 说到做到",
     "你要说他答应的事都做到了。",
     ("Hij komt zijn afspraken altijd na.", "Kom je afspraken na."),
     ("een afspraak houden", "de belofte bewaren")),
    ("nlc-een-pauze-nemen", "een pauze nemen", "C", "core", "休息一下",
     "你提议先歇会儿。",
     ("Zullen we een pauze nemen?", "Ik neem even pauze."),
     ("een rust nemen", "pauze doen")),

    # ── D 手上的动作 ──────────────────────────────────────────────────────────
    ("nlc-de-deur-opendoen", "de deur opendoen", "D", "core", "开门(去把门打开)",
     "有人敲门,你去开。",
     ("Kun jij de deur opendoen?", "Ik doe wel open."),
     ("de deur openen maken", "de deur duwen open")),
    ("nlc-oppakken", "iets oppakken", "D", "core", "把东西捡起来",
     "东西掉地上了,你让人捡起来。",
     ("Kun je dat even oppakken?", "Hij pakte het van de grond op."),
     ("iets nemen van grond", "iets omhoog halen")),
    ("nlc-vasthouden", "iets vasthouden", "D", "core", "拿着 / 握住",
     "你请对方帮你拿一下。",
     ("Kun je dit even vasthouden?", "Hou het goed vast."),
     ("iets houden vast maken", "iets grijpen blijven")),
    ("nlc-laten-vallen", "iets laten vallen", "D", "mid", "失手掉落",
     "你手一滑把杯子摔了。",
     ("Ik liet mijn telefoon vallen.", "Pas op, niet laten vallen!"),
     ("iets vallen maken", "iets droppen")),
    ("nlc-weggooien", "iets weggooien", "D", "core", "扔掉",
     "你说那个盒子可以扔了。",
     ("Gooi het maar weg.", "Niet weggooien, ik heb het nog nodig."),
     ("iets weg doen gooien", "iets uit werpen")),
    ("nlc-aanzetten", "iets aanzetten", "D", "core", "打开(电器)",
     "你让人把电视打开。",
     ("Zet de tv even aan.", "De verwarming staat aan."),
     ("iets open zetten", "iets starten maken")),
    ("nlc-opschrijven", "iets opschrijven", "D", "mid", "记下来",
     "你怕忘,要把地址写下来。",
     ("Ik schrijf het even op.", "Schrijf het op, anders vergeet je het."),
     ("iets neer schrijven", "iets schrijven op")),
    ("nlc-uitdoen", "iets uitdoen", "D", "core", "关掉 / 脱掉",
     "你让人把灯关了。",
     ("Doe het licht uit.", "Doe je jas maar uit."),
     ("iets uit maken", "iets af zetten")),
)


def _phrases() -> list[Pattern]:
    return [
        Pattern(id=i, frame=f, group=g, level=lv, meaning=m, cue=c,
                examples=tuple(e), lang="nl", track="oneliner",
                group_label=_PHRASE_GROUPS[g])
        for i, f, g, lv, m, c, e in _RAW_PHRASES
    ]


def _collocations() -> list[Pattern]:
    return [
        Pattern(id=i, frame=f, group=g, level=lv, meaning=m, cue=c,
                examples=tuple(e), lang="nl", track="collocation",
                wrong=tuple(w), group_label=_SCENE_GROUPS[g])
        for i, f, g, lv, m, c, e, w in _RAW_COLLOCATIONS
    ]


#: 零基础阶段不做话语框架:能把一句整话说出来比什么都重要。
DUTCH = build_catalog("nl", "荷兰语", ("oneliner", "collocation"),
                      _phrases() + _collocations())
