"""荷兰语的练习清单:整句 + 搭配。

比英语那套刻意更朴素。英语练的是"读得懂但说不地道",所以有大量话语框架
(让步、收口、组织话语);荷兰语是零基础起步,这个阶段要的是**在真实场合里
把一句话说出来**,所以内容集中在日常场景,不碰那些高级的话语技巧。

* **句型**——带空位的框架,填进自己的内容就能造句(``Mag ik …?``)。
* **整句**——在荷兰真实会遇到的场合里,原样能用的一句话。点菜、问路、
  听不懂请对方再说一遍。
* **搭配**——动词和它常跟的名词,以及日常动作。荷兰语的难点在于动词往往
  跑到句尾、而且很多说法与英语不对应(``boodschappen doen`` 不是 do shopping)。

干扰项是中文直译或照英语套过来的版本——后者尤其常见:会英语的人学荷兰语,
第一反应就是把英语逐词换过去。
"""

from __future__ import annotations

from src.growth.catalog import Pattern, build_catalog
from src.growth.dutch_examples import EXAMPLE_MEANINGS

_PHRASE_GROUPS = {
    "A": "打招呼与客套",
    "B": "点餐与购物",
    "C": "问路与出行",
    "D": "听不懂与求助",
    "E": "约时间与安排",
    "F": "表态与回应",
    "G": "看病与办事",
    "H": "闲聊与社交",
}

_SCENE_GROUPS = {
    "A": "日常起居",
    "B": "出行与办事",
    "C": "工作与学习",
    "D": "手上的动作",
    "E": "身体与感受",
}

#: (id, 荷兰语, 分组, 难度, 释义, 情境, 例句)
_RAW_PHRASES: tuple[tuple, ...] = (
    # ── A 打招呼与客套 ────────────────────────────────────────────────────────
    ("nl-goedemorgen", "Goedemorgen.", "A", "core", "早上好",
     "你上午进店或进办公室,先打个招呼。",
     ("Goedemorgen! Alles goed?", "Goedemorgen, meneer.")),
    ("nl-hoe-gaat-het", "Hoe gaat het?", "A", "core", "你好吗?(最常用的寒暄)",
     "碰到熟人,你要问一句近况。",
     ("Hé, hoe gaat het?", "Hoe gaat het met je?")),
    ("nl-goed-en-met-jou", "Goed, en met jou?", "A", "core", "挺好的,你呢?",
     "对方问你好不好,你答完要把问题递回去。",
     ("\"Hoe gaat het?\" \"Goed, en met jou?\"", "Prima, en met jou?")),
    ("nl-alsjeblieft", "Alsjeblieft.", "A", "core", "给你 / 请(递东西或提请求时)",
     "你把东西递给对方。",
     ("Hier, alsjeblieft.", "Mag ik de rekening, alsjeblieft?")),
    ("nl-dank-je-wel", "Dank je wel.", "A", "core", "谢谢(对熟人)",
     "别人帮了你一个小忙。",
     ("Dank je wel voor je hulp.", "Dank u wel, meneer.")),
    ("nl-graag-gedaan", "Graag gedaan.", "A", "core", "不客气",
     "对方向你道谢,你回一句。",
     ("\"Dank je wel!\" \"Graag gedaan.\"", "Geen dank, graag gedaan.")),
    ("nl-tot-ziens", "Tot ziens.", "A", "core", "再见(正式一点)",
     "你离开店里或结束一次正式会面。",
     ("Tot ziens, fijne dag!", "Tot ziens en bedankt.")),
    ("nl-tot-morgen", "Tot morgen.", "A", "core", "明天见",
     "下班时跟同事告别。",
     ("Tot morgen!", "Oké, tot morgen dan.")),
    ("nl-fijne-dag", "Fijne dag nog!", "A", "mid", "祝你今天愉快",
     "结账或道别时加一句客套。",
     ("Bedankt, fijne dag nog!", "Fijn weekend nog!")),
    ("nl-sorry", "Sorry, hoor.", "A", "mid", "不好意思(轻微致歉,很口语)",
     "你不小心挡了别人的路。",
     ("Sorry hoor, ik zag je niet.", "Sorry, dat was mijn fout.")),

    # ── B 点餐与购物 ──────────────────────────────────────────────────────────
    ("nl-mag-ik", "Mag ik …?", "B", "core", "我可以要……吗?(点东西最常用)",
     "你在咖啡店要点一杯咖啡。",
     ("Mag ik een koffie, alsjeblieft?", "Mag ik even kijken?")),
    ("nl-ik-wil-graag", "Ik wil graag …", "B", "core", "我想要……",
     "你在柜台说明你要什么。",
     ("Ik wil graag twee broodjes.", "Ik wil graag betalen.")),
    ("nl-wat-kost-dit", "Wat kost dit?", "B", "core", "这个多少钱?",
     "你拿着一样东西问价钱。",
     ("Wat kost dit?", "Wat kosten deze?")),
    ("nl-de-rekening", "De rekening, alsjeblieft.", "B", "core", "请结账",
     "吃完饭你要买单。",
     ("Mag ik de rekening, alsjeblieft?", "De rekening graag.")),
    ("nl-pinnen", "Kan ik pinnen?", "B", "core", "可以刷卡吗?(荷兰最常用的支付问法)",
     "你要确认这家店能不能刷卡。",
     ("Kan ik hier pinnen?", "Pinnen mag altijd.")),
    ("nl-een-moment", "Een moment, alstublieft.", "B", "mid", "请稍等一下",
     "你需要对方等几秒钟。",
     ("Een moment, ik pak het even.", "Momentje!")),
    ("nl-is-dat-alles", "Is dat alles?", "B", "mid", "就这些吗?",
     "店员问你还要不要别的。",
     ("\"Is dat alles?\" \"Ja, dat is alles.\"", "Verder nog iets?")),
    ("nl-ik-kijk-even", "Ik kijk even rond.", "B", "mid", "我先随便看看",
     "店员来问要不要帮忙,你只是想逛逛。",
     ("Dank je, ik kijk even rond.", "Ik kijk alleen even.")),

    # ── C 问路与出行 ──────────────────────────────────────────────────────────
    ("nl-waar-is", "Waar is …?", "C", "core", "……在哪里?",
     "你要问洗手间在哪。",
     ("Waar is het station?", "Waar is de wc?")),
    ("nl-hoe-kom-ik", "Hoe kom ik bij …?", "C", "core", "我怎么去……?",
     "你要问去中央车站怎么走。",
     ("Hoe kom ik bij het centraal station?", "Hoe kom ik daar het snelst?")),
    ("nl-rechtdoor", "Rechtdoor en dan links.", "C", "core", "直走然后左转",
     "你要给别人指路。",
     ("Rechtdoor en dan rechts.", "Ga rechtdoor tot het kruispunt.")),
    ("nl-hoe-ver", "Hoe ver is het?", "C", "core", "还有多远?",
     "你想知道还要走多久。",
     ("Hoe ver is het lopen?", "Is het ver hiervandaan?")),
    ("nl-welk-spoor", "Welk spoor?", "C", "mid", "几号站台?",
     "你在火车站要确认站台。",
     ("Welk spoor is het?", "Spoor vijf, geloof ik.")),
    ("nl-hoe-laat", "Hoe laat vertrekt de trein?", "C", "mid", "火车几点开?",
     "你要确认发车时间。",
     ("Hoe laat vertrekt de trein?", "Hoe laat begint het?")),
    ("nl-ik-ben-verdwaald", "Ik ben verdwaald.", "C", "mid", "我迷路了",
     "你找不到方向,得向人求助。",
     ("Sorry, ik ben verdwaald.", "We zijn een beetje verdwaald.")),

    # ── D 听不懂与求助 ────────────────────────────────────────────────────────
    ("nl-kun-je-herhalen", "Kun je dat herhalen?", "D", "core", "能再说一遍吗?",
     "对方说太快你没听清。",
     ("Sorry, kun je dat herhalen?", "Kunt u dat herhalen, alstublieft?")),
    ("nl-langzamer", "Kun je wat langzamer praten?", "D", "core", "能说慢一点吗?",
     "你跟得上单词但跟不上语速。",
     ("Sorry, kun je wat langzamer praten?", "Iets langzamer, alsjeblieft.")),
    ("nl-ik-begrijp-het-niet", "Ik begrijp het niet.", "D", "core", "我没听懂",
     "你完全没理解对方的意思。",
     ("Sorry, ik begrijp het niet.", "Ik begrijp het nu wel.")),
    ("nl-wat-betekent", "Wat betekent dat?", "D", "core", "那是什么意思?",
     "你听到一个不认识的词。",
     ("Wat betekent dat woord?", "Wat betekent \"gezellig\"?")),
    ("nl-spreekt-u-engels", "Spreekt u Engels?", "D", "core", "您会说英语吗?",
     "你实在说不下去了,要换语言。",
     ("Sorry, spreekt u Engels?", "Spreek je Engels?")),
    ("nl-ik-leer-nog", "Ik leer het nog.", "D", "mid", "我还在学(所以说得慢)",
     "你要说明自己是初学者。",
     ("Sorry, ik leer het nog.", "Mijn Nederlands is nog niet zo goed.")),
    ("nl-hoe-zeg-je", "Hoe zeg je dat in het Nederlands?", "D", "mid", "这个荷兰语怎么说?",
     "你想问一个词的荷兰语说法。",
     ("Hoe zeg je dat in het Nederlands?", "Hoe schrijf je dat?")),
    ("nl-kun-je-me-helpen", "Kun je me helpen?", "D", "core", "你能帮我一下吗?",
     "你需要别人搭把手。",
     ("Kun je me even helpen?", "Kunt u mij helpen, alstublieft?")),

    # ── E 约时间与安排 ────────────────────────────────────────────────────────
    ("nl-zullen-we", "Zullen we …?", "E", "core", "我们要不要……?(提议)",
     "你想约对方一起去喝一杯。",
     ("Zullen we koffie drinken?", "Zullen we gaan?")),
    ("nl-heb-je-tijd", "Heb je tijd?", "E", "core", "你有空吗?",
     "你想约对方见面。",
     ("Heb je morgen tijd?", "Heb je even tijd?")),
    ("nl-het-komt-niet-uit", "Het komt me niet uit.", "E", "mid", "这个时间我不方便",
     "对方提的时间你去不了。",
     ("Sorry, het komt me niet uit.", "Vrijdag komt me beter uit.")),
    ("nl-tot-dan", "Tot dan!", "E", "core", "到时候见",
     "约好了时间,你收尾一句。",
     ("Oké, tot dan!", "Prima, tot dan.")),
    ("nl-ik-ben-wat-later", "Ik ben wat later.", "E", "mid", "我会晚一点到",
     "你在路上要通知对方。",
     ("Sorry, ik ben wat later.", "Ik ben tien minuten later.")),

    # ── F 表态与回应 ──────────────────────────────────────────────────────────
    ("nl-dat-klopt", "Dat klopt.", "F", "core", "没错 / 是这样",
     "对方说的信息是对的,你确认一句。",
     ("\"Je woont in Amsterdam?\" \"Dat klopt.\"", "Dat klopt niet.")),
    ("nl-geen-probleem", "Geen probleem.", "F", "core", "没问题 / 没事",
     "对方为一件小事道歉。",
     ("\"Sorry!\" \"Geen probleem.\"", "Dat is geen probleem.")),
    ("nl-prima", "Prima!", "F", "core", "挺好 / 可以(爽快同意)",
     "对方提了个安排,你答应。",
     ("\"Zullen we om zeven uur?\" \"Prima!\"", "Dat is prima.")),
    ("nl-ik-weet-het-niet", "Ik weet het niet.", "F", "core", "我不知道",
     "被问到你答不上来的事。",
     ("Sorry, ik weet het niet.", "Ik weet het echt niet.")),
    ("nl-misschien", "Misschien.", "F", "core", "也许吧(不把话说死)",
     "你还不确定去不去。",
     ("Misschien, ik laat het weten.", "Misschien morgen.")),
    ("nl-dat-hangt-ervan-af", "Dat hangt ervan af.", "F", "mid", "那要看情况",
     "答案取决于别的条件。",
     ("Dat hangt ervan af hoe laat het is.", "Dat hangt van het weer af.")),
    ("nl-ik-denk-het-wel", "Ik denk het wel.", "F", "mid", "我觉得应该是",
     "你比较确定但不绝对。",
     ("\"Komt hij ook?\" \"Ik denk het wel.\"", "Ik denk het niet.")),
    ("nl-wat-jammer", "Wat jammer!", "F", "mid", "太可惜了",
     "对方说了一件遗憾的事。",
     ("Wat jammer dat je niet kunt.", "Jammer, volgende keer dan.")),
    ("nl-gezellig", "Gezellig!", "F", "mid", "真惬意 / 气氛真好(荷兰语的招牌词)",
     "你和朋友坐下来喝酒聊天,气氛很好。",
     ("Wat gezellig!", "Het was heel gezellig, bedankt.")),
    ("nl-doe-maar", "Doe maar.", "F", "mid", "那就这样吧 / 来一个吧",
     "店员问要不要加一份,你同意。",
     ("\"Nog een biertje?\" \"Doe maar.\"", "Doe maar twee.")),
    ("nl-laat-maar", "Laat maar.", "F", "mid", "算了,不用了",
     "你本来要说的事不重要了。",
     ("Laat maar, het is niet belangrijk.", "Laat maar zitten.")),
    ("nl-het-geeft-niet", "Het geeft niet.", "F", "mid", "没关系(安慰对方)",
     "对方因为一件小事很过意不去。",
     ("\"Sorry, ik was het vergeten.\" \"Het geeft niet.\"", "Geeft niks hoor.")),

    # ── 补充:句型(带空位,填进自己的内容) ──────────────────────────────────
    ("nl-ik-zoek", "Ik zoek …", "B", "core", "我在找……",
     "你在店里找某样东西,要开口问。",
     ("Ik zoek een kado voor mijn moeder.", "Ik zoek de uitgang.")),
    ("nl-heeft-u", "Heeft u …?", "B", "core", "你们有……吗?",
     "你想问店里有没有某样东西。",
     ("Heeft u dit in maat 42?", "Heeft u ook koffie zonder suiker?")),
    ("nl-ik-heb-nodig", "Ik heb … nodig.", "B", "core", "我需要……",
     "你要说明自己缺什么。",
     ("Ik heb een nieuwe fiets nodig.", "Ik heb meer tijd nodig.")),
    ("nl-kan-ik", "Kan ik …?", "B", "core", "我能……吗?",
     "你要问一件事能不能做。",
     ("Kan ik hier parkeren?", "Kan ik dit ruilen?")),
    ("nl-zou-je-kunnen", "Zou je … kunnen?", "D", "mid", "你能不能……?(更客气的请求)",
     "你要礼貌地请人帮个忙。",
     ("Zou je me kunnen helpen?", "Zou je dat kunnen herhalen?")),
    ("nl-mag-ik-vragen", "Mag ik vragen …?", "D", "mid", "我可以问一下……吗?",
     "你要问一个稍微私人的问题。",
     ("Mag ik vragen hoe oud je bent?", "Mag ik vragen waarom?")),
    ("nl-ik-denk-dat", "Ik denk dat …", "F", "core", "我觉得……",
     "你要给出自己的看法。",
     ("Ik denk dat het gaat regenen.", "Ik denk dat hij gelijk heeft.")),
    ("nl-ik-vind", "Ik vind … leuk.", "F", "core", "我喜欢……",
     "你要表达喜好。",
     ("Ik vind dit heel leuk.", "Ik vind hem aardig.")),
    ("nl-ik-hou-van", "Ik hou van …", "F", "core", "我很喜欢 / 我爱……",
     "你要说你很爱某样东西。",
     ("Ik hou van koffie.", "Ik hou niet van kou.")),
    ("nl-ik-moet", "Ik moet …", "E", "core", "我得……(必须做某事)",
     "你要说明你有事得先走。",
     ("Ik moet nu gaan.", "Ik moet nog werken.")),
    ("nl-ik-ga", "Ik ga … ", "E", "core", "我要去……",
     "你要说你接下来去做什么。",
     ("Ik ga naar huis.", "Ik ga even boodschappen doen.")),
    ("nl-ik-wil-niet", "Ik wil liever …", "F", "mid", "我更想……",
     "两个选项里你偏向一个。",
     ("Ik wil liever thuisblijven.", "Ik drink liever thee.")),
    ("nl-heb-je-zin", "Heb je zin om …?", "H", "mid", "你想不想……?(发出邀请)",
     "你要约对方一起做点什么。",
     ("Heb je zin om koffie te drinken?", "Heb je zin in een film?")),
    ("nl-wat-voor", "Wat voor … ?", "B", "mid", "什么样的……?",
     "你要问对方具体想要哪一种。",
     ("Wat voor muziek luister je?", "Wat voor werk doe je?")),
    ("nl-hoeveel", "Hoeveel … ?", "B", "core", "多少……?",
     "你要问数量。",
     ("Hoeveel kost het?", "Hoeveel mensen komen er?")),
    ("nl-wanneer", "Wanneer … ?", "E", "core", "什么时候……?",
     "你要问时间。",
     ("Wanneer begint het?", "Wanneer ben je terug?")),
    ("nl-waarom", "Waarom … ?", "F", "core", "为什么……?",
     "你要追问原因。",
     ("Waarom is het dicht?", "Waarom niet?")),
    ("nl-weet-je-of", "Weet je of …?", "D", "mid", "你知道……吗?",
     "你要打听一件不确定的事。",
     ("Weet je of de winkel open is?", "Weet je of hij komt?")),
    ("nl-het-is-te", "Het is te …", "F", "mid", "太……了(超过了合适的程度)",
     "你要说某样东西过头了。",
     ("Het is te duur.", "Het is te koud buiten.")),
    ("nl-er-is", "Er is / Er zijn …", "C", "core", "有……(存在)",
     "你要说某个地方有什么。",
     ("Er is een supermarkt om de hoek.", "Er zijn geen plaatsen meer.")),
    ("nl-ik-ben-aan-het", "Ik ben … aan het doen.", "C", "high", "我正在做……(进行时)",
     "你要说你此刻正忙着什么。",
     ("Ik ben aan het koken.", "Hij is aan het werken.")),
    ("nl-zullen-we-samen", "Zal ik … ?", "E", "mid", "要不要我来……?(主动提供帮助)",
     "你想帮对方做一件事,先问一句。",
     ("Zal ik je helpen?", "Zal ik even bellen?")),

    # ── 补充:整句 ────────────────────────────────────────────────────────────
    ("nl-hallo", "Hallo!", "A", "core", "你好(最通用的招呼)",
     "你见到人打个招呼。",
     ("Hallo, alles goed?", "Hallo daar!")),
    ("nl-hoi", "Hoi!", "A", "core", "嗨(朋友之间)",
     "你跟熟人打招呼。",
     ("Hoi, lang niet gezien!", "Hoi, hoe is het?")),
    ("nl-goedemiddag", "Goedemiddag.", "A", "core", "下午好",
     "你下午进店或进办公室。",
     ("Goedemiddag, mevrouw.", "Goedemiddag allemaal.")),
    ("nl-goedenavond", "Goedenavond.", "A", "core", "晚上好",
     "你晚上到达一个场合。",
     ("Goedenavond, welkom.", "Goedenavond samen.")),
    ("nl-welterusten", "Welterusten.", "A", "core", "晚安(睡前)",
     "你要去睡了,跟家人道别。",
     ("Welterusten, slaap lekker.", "Welterusten allemaal.")),
    ("nl-tot-straks", "Tot straks!", "A", "core", "一会儿见",
     "你出门一会儿就回来。",
     ("Tot straks!", "Oké, tot straks dan.")),
    ("nl-fijn-weekend", "Fijn weekend!", "A", "mid", "周末愉快",
     "周五下班时跟同事道别。",
     ("Fijn weekend, tot maandag!", "Jij ook een fijn weekend.")),
    ("nl-aangenaam", "Aangenaam.", "A", "mid", "幸会(初次见面)",
     "你被介绍给一个新认识的人。",
     ("Aangenaam kennis te maken.", "Aangenaam, ik ben Liang.")),
    ("nl-pardon", "Pardon?", "A", "core", "什么?/ 借过(没听清或要让路)",
     "你没听清对方说什么。",
     ("Pardon? Wat zei je?", "Pardon, mag ik erlangs?")),
    ("nl-excuseer", "Mag ik er even langs?", "A", "mid", "借过一下",
     "车厢或人群里你要挤过去。",
     ("Sorry, mag ik er even langs?", "Mag ik erlangs, alstublieft?")),
    ("nl-bedankt", "Bedankt!", "A", "core", "谢了(比正式的说法更随意)",
     "别人帮了你,你简短道谢。",
     ("Bedankt voor alles!", "Alvast bedankt.")),
    ("nl-geen-dank", "Geen dank.", "A", "mid", "不用谢",
     "对方道谢,你客气一句。",
     ("\"Bedankt!\" \"Geen dank.\"", "Geen dank, hoor.")),
    ("nl-smakelijk", "Eet smakelijk!", "B", "core", "慢用 / 吃好(上菜时说)",
     "大家开动前互相说一句。",
     ("Eet smakelijk!", "Smakelijk eten!")),
    ("nl-proost", "Proost!", "B", "core", "干杯",
     "大家举杯。",
     ("Proost, op jou!", "Proost allemaal!")),
    ("nl-lekker", "Dat was lekker.", "B", "core", "很好吃",
     "你吃完要夸一句。",
     ("Dat was echt lekker.", "Het smaakt lekker.")),
    ("nl-nog-een", "Nog een, alsjeblieft.", "B", "core", "再来一个",
     "你要再点一杯。",
     ("Nog een biertje, alsjeblieft.", "Mag ik er nog een?")),
    ("nl-voor-hier", "Voor hier of om mee te nemen?", "B", "mid", "堂食还是带走?",
     "店员问你在店里吃还是外带。",
     ("\"Voor hier of om mee te nemen?\" \"Om mee te nemen.\"",
      "Om mee te nemen, graag.")),
    ("nl-apart-betalen", "Kunnen we apart betalen?", "B", "mid", "能分开付吗?",
     "你们几个人要各付各的。",
     ("Kunnen we apart betalen?", "Samen of apart?")),
    ("nl-ik-ben-op-zoek", "Waar kan ik … vinden?", "B", "mid", "我在哪儿能找到……?",
     "你在超市找不到某样东西。",
     ("Waar kan ik de melk vinden?", "Waar kan ik een pinautomaat vinden?")),
    ("nl-is-het-ver", "Is het ver lopen?", "C", "mid", "走过去远吗?",
     "你想知道该走路还是坐车。",
     ("Is het ver lopen vanaf hier?", "Nee, vijf minuten.")),
    ("nl-welke-bus", "Welke bus moet ik nemen?", "C", "mid", "我该坐哪路车?",
     "你在站台不知道坐哪一班。",
     ("Welke bus moet ik nemen naar het centrum?", "Welke tram gaat erheen?")),
    ("nl-moet-ik-overstappen", "Moet ik overstappen?", "C", "mid", "需要换乘吗?",
     "你要确认这趟车直达不直达。",
     ("Moet ik overstappen?", "Je moet overstappen in Utrecht.")),
    ("nl-is-deze-plek-vrij", "Is deze plek vrij?", "C", "core", "这个位子有人吗?",
     "车上或咖啡店你想坐下。",
     ("Is deze plek vrij?", "Ja hoor, ga je gang.")),
    ("nl-ga-je-gang", "Ga je gang.", "F", "mid", "请便 / 你先来",
     "你示意对方可以继续或先行。",
     ("Ga je gang!", "Gaat uw gang, mevrouw.")),
    ("nl-sorry-dat-ik-stoor", "Sorry dat ik stoor.", "D", "mid", "不好意思打扰了",
     "你要打断正在忙的人。",
     ("Sorry dat ik stoor, heb je even?", "Sorry dat ik stoor.")),
    ("nl-wat-zei-je", "Wat zei je?", "D", "core", "你刚说什么?",
     "你没听清对方的话。",
     ("Sorry, wat zei je?", "Wat zei u, mevrouw?")),
    ("nl-ik-versta-je-niet", "Ik versta je niet.", "D", "core", "我听不清你说的",
     "环境太吵或对方说太轻。",
     ("Sorry, ik versta je niet.", "Ik verstond het niet goed.")),
    ("nl-kun-je-het-opschrijven", "Kun je het opschrijven?", "D", "mid", "能写下来吗?",
     "你听不懂,想让对方写出来。",
     ("Kun je het even opschrijven?", "Schrijf het maar op.")),
    ("nl-geen-haast", "Geen haast.", "E", "mid", "不着急",
     "你请人帮忙但不想催。",
     ("Geen haast hoor.", "Er is geen haast bij.")),
    ("nl-schikt-het", "Schikt het zo?", "E", "high", "这样方便吗?",
     "你提了个时间,问对方合不合适。",
     ("Schikt het om drie uur?", "Als het schikt.")),
    ("nl-ik-kan-niet", "Ik kan helaas niet.", "E", "core", "我恐怕去不了",
     "你要婉拒一个邀请。",
     ("Ik kan helaas niet, sorry.", "Helaas kan ik niet komen.")),
    ("nl-volgende-keer", "Volgende keer!", "E", "core", "下次吧",
     "这次去不了,但表示还想去。",
     ("Jammer, volgende keer!", "Volgende keer zeker.")),
    ("nl-natuurlijk", "Natuurlijk!", "F", "core", "当然",
     "对方问你能不能,你爽快答应。",
     ("\"Mag ik even?\" \"Natuurlijk!\"", "Natuurlijk niet.")),
    ("nl-zeker-weten", "Zeker weten!", "F", "mid", "那还用说 / 肯定的",
     "你要强调非常确定。",
     ("\"Kom je ook?\" \"Zeker weten!\"", "Weet je het zeker?")),
    ("nl-helemaal-mee-eens", "Helemaal mee eens.", "F", "mid", "完全同意",
     "对方说了一句你很认同的话。",
     ("Daar ben ik het helemaal mee eens.", "Mee eens!")),
    ("nl-dat-valt-mee", "Dat valt mee.", "F", "high", "没想象中那么糟",
     "事情比预期的好,你松口气。",
     ("\"Is het druk?\" \"Nee, dat valt mee.\"", "Dat viel me mee.")),
    ("nl-dat-valt-tegen", "Dat valt tegen.", "F", "high", "比预想的差",
     "结果让人有点失望。",
     ("Het weer valt tegen.", "Dat viel me tegen.")),
    ("nl-geen-idee", "Geen idee.", "F", "core", "完全不知道",
     "被问到你一点头绪都没有的事。",
     ("\"Hoe laat komt hij?\" \"Geen idee.\"", "Echt geen idee.")),
    ("nl-het-maakt-niet-uit", "Het maakt niet uit.", "F", "core", "都行 / 无所谓",
     "对方让你选,你没偏好。",
     ("Het maakt mij niet uit.", "Maakt niet uit.")),
    ("nl-wat-leuk", "Wat leuk!", "H", "core", "真不错 / 真有意思",
     "对方分享了一件好事。",
     ("Wat leuk voor je!", "Wat leuk om te horen.")),
    ("nl-succes", "Succes!", "H", "core", "祝你顺利",
     "对方要去面试或考试。",
     ("Succes morgen!", "Veel succes!")),
    ("nl-beterschap", "Beterschap!", "H", "mid", "早日康复",
     "对方生病了。",
     ("Beterschap, hoor!", "Veel beterschap.")),
    ("nl-gefeliciteerd", "Gefeliciteerd!", "H", "core", "恭喜",
     "对方过生日或有喜事。",
     ("Gefeliciteerd met je verjaardag!", "Gefeliciteerd!")),
    ("nl-lang-niet-gezien", "Lang niet gezien!", "H", "mid", "好久不见",
     "碰到很久没见的朋友。",
     ("Hé, lang niet gezien!", "Lang niet gezien, hoe gaat het?")),
    ("nl-doe-de-groeten", "Doe de groeten!", "H", "mid", "代我问好",
     "你托对方向家人问好。",
     ("Doe de groeten aan je vrouw.", "Doe de groeten thuis!")),
    ("nl-wat-een-weer", "Wat een weer!", "H", "mid", "这什么鬼天气(万能闲聊)",
     "外面下大雨刮大风。",
     ("Wat een weer, zeg!", "Lekker weertje vandaag.")),
    ("nl-druk", "Het is druk.", "H", "core", "人很多 / 很忙",
     "店里或路上人特别多。",
     ("Het is heel druk vandaag.", "Ik heb het druk.")),
    ("nl-ik-ben-ziek", "Ik ben ziek.", "G", "core", "我病了",
     "你要请病假。",
     ("Ik ben ziek, ik kom niet.", "Hij is al een week ziek.")),
    ("nl-ik-heb-pijn", "Ik heb pijn in …", "G", "core", "我……疼",
     "你要跟医生说哪里不舒服。",
     ("Ik heb pijn in mijn rug.", "Ik heb keelpijn.")),
    ("nl-ik-voel-me-niet-goed", "Ik voel me niet goed.", "G", "core", "我不太舒服",
     "你忽然觉得身体不适。",
     ("Ik voel me niet zo goed.", "Voel je je beter?")),
    ("nl-huisarts", "Ik wil een afspraak met de huisarts.", "G", "mid", "我想约家庭医生",
     "你打电话给诊所预约。",
     ("Ik wil graag een afspraak met de huisarts.", "Heeft u een huisarts?")),
    ("nl-apotheek", "Waar is de dichtstbijzijnde apotheek?", "G", "mid", "最近的药店在哪?",
     "你要去买药。",
     ("Waar is de dichtstbijzijnde apotheek?", "De apotheek is om de hoek.")),
    ("nl-zonder-recept", "Is dit zonder recept?", "G", "high", "这个不用处方吗?",
     "你在药店问药能不能直接买。",
     ("Is dit zonder recept te krijgen?", "Daar heb je een recept voor nodig.")),
    ("nl-ik-woon-in", "Ik woon in …", "H", "core", "我住在……",
     "别人问你住哪儿。",
     ("Ik woon in Amsterdam.", "Waar woon je?")),
    ("nl-ik-kom-uit", "Ik kom uit …", "H", "core", "我来自……",
     "别人问你是哪里人。",
     ("Ik kom uit China.", "Waar kom je vandaan?")),
    ("nl-ik-werk-bij", "Ik werk bij …", "H", "core", "我在……工作",
     "别人问你做什么工作。",
     ("Ik werk bij een bank.", "Waar werk je?")),
    ("nl-ik-leer-nederlands", "Ik leer Nederlands.", "H", "core", "我在学荷兰语",
     "你要说明自己正在学。",
     ("Ik leer Nederlands sinds een jaar.", "Hoe lang leer je al Nederlands?")),
)
#: (id, 荷兰语, 分组, 难度, 释义, 情境, 例句, 错误版)
_RAW_COLLOCATIONS: tuple[tuple, ...] = (
    # ── A 日常起居 ────────────────────────────────────────────────────────────
    ("nlc-boodschappen-doen", "boodschappen doen", "A", "core", "买菜 / 采购日用品",
     "你要说下班后得去超市。",
     ("Ik moet nog boodschappen doen.", "Zullen we samen boodschappen doen?"),
     ("inkopen maken", "winkelen doen")),
    ("nlc-koffie-zetten", "koffie zetten", "A", "core", "煮咖啡",
     "你要问对方要不要煮壶咖啡。",
     ("Zal ik koffie zetten?", "Hij zet elke ochtend koffie."),
     ("koffie maken", "koffie koken")),
    ("nlc-afwassen", "de afwas doen", "A", "core", "洗碗",
     "你说饭后由你收拾。",
     ("Ik doe de afwas wel.", "Wie doet vandaag de afwas?"),
     ("de borden wassen", "schotels schoonmaken")),
    ("nlc-de-was-doen", "de was doen", "A", "core", "洗衣服",
     "你说这周末得洗衣服。",
     ("Ik moet de was nog doen.", "De was hangt buiten."),
     ("kleren wassen maken", "wasgoed doen")),
    ("nlc-opruimen", "opruimen", "A", "core", "收拾 / 整理",
     "你要说把桌子收拾一下。",
     ("Kun je even opruimen?", "Ik heb de kamer opgeruimd."),
     ("schoon maken alles", "orde maken")),
    ("nlc-het-licht-aandoen", "het licht aandoen", "A", "core", "开灯",
     "屋里太暗,你让人开灯。",
     ("Doe het licht even aan.", "Vergeet niet het licht uit te doen."),
     ("het licht openen", "de lamp open maken")),
    ("nlc-de-deur-dichtdoen", "de deur dichtdoen", "A", "core", "关门",
     "你让对方把门带上。",
     ("Doe de deur even dicht.", "De deur staat open."),
     ("de deur sluiten maken", "de deur close doen")),
    ("nlc-slapen-gaan", "naar bed gaan", "A", "core", "去睡觉",
     "你说你要去睡了。",
     ("Ik ga naar bed.", "Hij gaat altijd laat naar bed."),
     ("gaan slapen bed", "naar slaap gaan")),

    # ── B 出行与办事 ──────────────────────────────────────────────────────────
    ("nlc-de-trein-nemen", "de trein nemen", "B", "core", "坐火车",
     "你要说你坐火车去。",
     ("Ik neem de trein naar Utrecht.", "Neem je de trein of de bus?"),
     ("de trein zitten", "met trein gaan nemen")),
    ("nlc-fietsen", "op de fiets gaan", "B", "core", "骑车去",
     "你说骑自行车过去更快。",
     ("Ik ga op de fiets.", "Zullen we op de fiets gaan?"),
     ("fiets rijden gaan", "met fiets zitten")),
    ("nlc-een-afspraak-maken", "een afspraak maken", "B", "core", "约个时间 / 预约",
     "你要跟医生约时间。",
     ("Ik wil een afspraak maken.", "We hebben een afspraak om drie uur."),
     ("een afspraak doen", "tijd maken met")),
    ("nlc-geld-pinnen", "geld pinnen", "B", "mid", "取现金",
     "你要先去取点钱。",
     ("Ik moet even geld pinnen.", "Kun je hier geld pinnen?"),
     ("geld nemen uit", "cash halen")),
    ("nlc-een-formulier-invullen", "een formulier invullen", "B", "mid", "填表",
     "办事时要填一张表格。",
     ("Je moet dit formulier invullen.", "Heb je het formulier al ingevuld?"),
     ("een formulier schrijven", "het formulier vol maken")),
    ("nlc-huur-betalen", "de huur betalen", "B", "mid", "交房租",
     "你要说月初要交房租。",
     ("De huur moet voor de eerste betaald zijn.", "Ik heb de huur al betaald."),
     ("huis geld geven", "de huur doen")),

    # ── C 工作与学习 ──────────────────────────────────────────────────────────
    ("nlc-een-vraag-stellen", "een vraag stellen", "C", "core", "提问",
     "你要在课上问一个问题。",
     ("Mag ik een vraag stellen?", "Hij stelde een goede vraag."),
     ("een vraag vragen", "een vraag maken")),
    ("nlc-aandacht-besteden", "aandacht besteden aan", "C", "mid", "注意 / 留心",
     "你要提醒对方留意细节。",
     ("Besteed aandacht aan de details.", "Hij besteedt er geen aandacht aan."),
     ("aandacht geven op", "attentie betalen")),
    ("nlc-een-fout-maken", "een fout maken", "C", "core", "犯错",
     "你要承认自己弄错了。",
     ("Ik heb een fout gemaakt.", "Iedereen maakt fouten."),
     ("een fout doen", "verkeerd maken")),
    ("nlc-afspraak-nakomen", "een afspraak nakomen", "C", "high", "守约 / 说到做到",
     "你要说他答应的事都做到了。",
     ("Hij komt zijn afspraken altijd na.", "Kom je afspraken na."),
     ("een afspraak houden", "de belofte bewaren")),
    ("nlc-een-pauze-nemen", "een pauze nemen", "C", "core", "休息一下",
     "你提议先歇会儿。",
     ("Zullen we een pauze nemen?", "Ik neem even pauze."),
     ("een rust nemen", "pauze doen")),

    # ── D 手上的动作 ──────────────────────────────────────────────────────────
    ("nlc-de-deur-opendoen", "de deur opendoen", "D", "core", "开门(去把门打开)",
     "有人敲门,你去开。",
     ("Kun jij de deur opendoen?", "Ik doe wel open."),
     ("de deur openen maken", "de deur duwen open")),
    ("nlc-oppakken", "iets oppakken", "D", "core", "把东西捡起来",
     "东西掉地上了,你让人捡起来。",
     ("Kun je dat even oppakken?", "Hij pakte het van de grond op."),
     ("iets nemen van grond", "iets omhoog halen")),
    ("nlc-vasthouden", "iets vasthouden", "D", "core", "拿着 / 握住",
     "你请对方帮你拿一下。",
     ("Kun je dit even vasthouden?", "Hou het goed vast."),
     ("iets houden vast maken", "iets grijpen blijven")),
    ("nlc-laten-vallen", "iets laten vallen", "D", "mid", "失手掉落",
     "你手一滑把杯子摔了。",
     ("Ik liet mijn telefoon vallen.", "Pas op, niet laten vallen!"),
     ("iets vallen maken", "iets droppen")),
    ("nlc-weggooien", "iets weggooien", "D", "core", "扔掉",
     "你说那个盒子可以扔了。",
     ("Gooi het maar weg.", "Niet weggooien, ik heb het nog nodig."),
     ("iets weg doen gooien", "iets uit werpen")),
    ("nlc-aanzetten", "iets aanzetten", "D", "core", "打开(电器)",
     "你让人把电视打开。",
     ("Zet de tv even aan.", "De verwarming staat aan."),
     ("iets open zetten", "iets starten maken")),
    ("nlc-opschrijven", "iets opschrijven", "D", "mid", "记下来",
     "你怕忘,要把地址写下来。",
     ("Ik schrijf het even op.", "Schrijf het op, anders vergeet je het."),
     ("iets neer schrijven", "iets schrijven op")),
    ("nlc-uitdoen", "iets uitdoen", "D", "core", "关掉 / 脱掉",
     "你让人把灯关了。",
     ("Doe het licht uit.", "Doe je jas maar uit."),
     ("iets uit maken", "iets af zetten")),

    # ── 补充:日常起居 ────────────────────────────────────────────────────────
    ("nlc-eten-koken", "eten koken", "A", "core", "做饭",
     "你说今晚你来做饭。",
     ("Ik kook vanavond.", "Hij kookt elke dag."),
     ("eten maken", "voedsel doen")),
    ("nlc-tafel-dekken", "de tafel dekken", "A", "mid", "摆餐具 / 布置餐桌",
     "吃饭前你让人摆好碗筷。",
     ("Kun je de tafel dekken?", "De tafel is gedekt."),
     ("de tafel klaar maken", "borden op tafel zetten")),
    ("nlc-stofzuigen", "stofzuigen", "A", "mid", "吸尘 / 用吸尘器打扫",
     "你说周末要吸一下地。",
     ("Ik ga even stofzuigen.", "Heb je al gestofzuigd?"),
     ("stof zuigen maken", "schoonmaken met machine")),
    ("nlc-de-vuilnis-buitenzetten", "de vuilnis buitenzetten", "A", "mid", "把垃圾拿出去",
     "今晚收垃圾,你得把袋子放到外面。",
     ("Vergeet de vuilnis niet buiten te zetten.", "Ik zet de vuilnis buiten."),
     ("vuilnis weg gooien buiten", "afval uit doen")),
    ("nlc-de-planten-water-geven", "de planten water geven", "A", "core", "给植物浇水",
     "你出门前要浇花。",
     ("Kun je de planten water geven?", "Ik heb ze al water gegeven."),
     ("water op de planten doen", "de planten drinken geven")),
    ("nlc-de-gordijnen-dichtdoen", "de gordijnen dichtdoen", "A", "mid", "拉上窗帘",
     "天黑了你要把窗帘拉上。",
     ("Doe je de gordijnen dicht?", "De gordijnen zijn open."),
     ("de gordijnen sluiten maken", "het raam bedekken")),
    ("nlc-de-verwarming-aanzetten", "de verwarming aanzetten", "A", "core", "开暖气",
     "屋里太冷,你要开暖气。",
     ("Zet de verwarming even aan.", "De verwarming staat uit."),
     ("de warmte open doen", "het vuur aan maken")),
    ("nlc-een-douche-nemen", "een douche nemen", "A", "core", "洗澡(淋浴)",
     "你说你先去冲个澡。",
     ("Ik ga even douchen.", "Hij neemt elke ochtend een douche."),
     ("een bad nemen douche", "wassen onder water")),
    ("nlc-tanden-poetsen", "tanden poetsen", "A", "core", "刷牙",
     "你提醒孩子睡前刷牙。",
     ("Heb je je tanden gepoetst?", "Ik poets twee keer per dag mijn tanden."),
     ("tanden wassen", "tanden schoon maken")),
    ("nlc-de-was-ophangen", "de was ophangen", "A", "mid", "晾衣服",
     "洗完衣服你要晾起来。",
     ("Ik hang de was even op.", "De was hangt buiten."),
     ("de kleren hangen op", "wasgoed buiten doen")),

    # ── 补充:出行与办事 ──────────────────────────────────────────────────────
    ("nlc-een-kaartje-kopen", "een kaartje kopen", "B", "core", "买票",
     "你在车站买车票。",
     ("Ik moet nog een kaartje kopen.", "Waar kan ik een kaartje kopen?"),
     ("een ticket nemen", "een kaartje halen maken")),
    ("nlc-inchecken", "inchecken", "B", "core", "刷卡进站 / 办理登机",
     "进地铁前要刷卡。",
     ("Vergeet niet in te checken.", "Ik ben vergeten uit te checken."),
     ("in checken doen", "kaart scannen in")),
    ("nlc-de-weg-vragen", "de weg vragen", "B", "mid", "问路",
     "你迷路了,要找人问。",
     ("Ik ga even de weg vragen.", "Hij vroeg mij de weg."),
     ("de richting vragen", "weg vragen aan")),
    ("nlc-een-pakje-ophalen", "een pakje ophalen", "B", "mid", "取快递",
     "包裹到了取件点,你要去拿。",
     ("Ik moet nog een pakje ophalen.", "Het pakje ligt bij de buren."),
     ("een pakket nemen op", "pakje halen uit")),
    ("nlc-een-rekening-openen", "een rekening openen", "B", "high", "开银行账户",
     "你刚到荷兰要开户。",
     ("Ik wil een rekening openen.", "Hij heeft een rekening geopend."),
     ("een account maken", "bank rekening doen")),
    ("nlc-zich-inschrijven", "zich inschrijven", "B", "high", "登记注册(市政厅、课程)",
     "你要去市政厅登记地址。",
     ("Je moet je inschrijven bij de gemeente.", "Ik heb me ingeschreven voor de cursus."),
     ("zich registreren maken", "naam opschrijven bij")),
    ("nlc-een-afspraak-afzeggen", "een afspraak afzeggen", "B", "mid", "取消约好的事",
     "你去不了了,要取消预约。",
     ("Ik moet de afspraak afzeggen.", "Hij heeft afgezegd."),
     ("een afspraak cancelen", "de afspraak weg doen")),
    ("nlc-in-de-rij-staan", "in de rij staan", "B", "core", "排队",
     "你在柜台前排了很久。",
     ("Je moet in de rij staan.", "We stonden een half uur in de rij."),
     ("in lijn wachten", "achter elkaar staan")),

    # ── 补充:工作与学习 ──────────────────────────────────────────────────────
    ("nlc-een-mail-sturen", "een mail sturen", "C", "core", "发邮件",
     "你说你回头发封邮件过去。",
     ("Ik stuur je een mail.", "Heb je de mail gestuurd?"),
     ("een mail zenden maken", "mail doen naar")),
    ("nlc-een-vergadering-hebben", "een vergadering hebben", "C", "core", "开会",
     "你说下午有个会。",
     ("Ik heb vanmiddag een vergadering.", "De vergadering duurde twee uur."),
     ("een meeting doen", "vergadering maken")),
    ("nlc-een-presentatie-geven", "een presentatie geven", "C", "mid", "做演示 / 做报告",
     "你下周要做个汇报。",
     ("Ik moet een presentatie geven.", "Zij gaf een goede presentatie."),
     ("een presentatie doen", "presentatie maken voor")),
    ("nlc-aantekeningen-maken", "aantekeningen maken", "C", "mid", "记笔记",
     "开会时你把要点记下来。",
     ("Ik maak even aantekeningen.", "Hij maakt nooit aantekeningen."),
     ("notities schrijven maken", "aantekening doen")),
    ("nlc-huiswerk-maken", "huiswerk maken", "C", "core", "做作业",
     "你说你得先把作业写完。",
     ("Ik moet nog huiswerk maken.", "Heb je je huiswerk af?"),
     ("huiswerk doen", "huis werk schrijven")),
    ("nlc-een-cursus-volgen", "een cursus volgen", "C", "mid", "上课 / 修一门课",
     "你在上荷兰语课。",
     ("Ik volg een cursus Nederlands.", "Hij volgt een avondcursus."),
     ("een cursus nemen", "les doen volgen")),
    ("nlc-examen-doen", "examen doen", "C", "mid", "参加考试",
     "你下周有考试。",
     ("Ik doe volgende week examen.", "Hij is geslaagd voor zijn examen."),
     ("examen nemen", "een test maken doen")),
    ("nlc-verlof-opnemen", "verlof opnemen", "C", "high", "休假 / 请假",
     "你要请几天假。",
     ("Ik neem volgende week verlof op.", "Hoeveel verlof heb je nog?"),
     ("vakantie nemen op", "vrij vragen dagen")),

    # ── 补充:手上的动作 ──────────────────────────────────────────────────────
    ("nlc-indrukken", "op een knop drukken", "D", "core", "按按钮",
     "你让人按一下那个按钮。",
     ("Druk op de groene knop.", "Je moet hier drukken."),
     ("een knop pushen", "de knop duwen in")),
    ("nlc-dichtdraaien", "de kraan dichtdraaien", "D", "core", "关水龙头",
     "水还在流,你让人关掉。",
     ("Draai de kraan dicht.", "De kraan lekt."),
     ("de kraan sluiten", "water dicht maken")),
    ("nlc-uitpakken", "iets uitpakken", "D", "mid", "拆开 / 打开包装",
     "快递到了,你要拆开。",
     ("Ik ga het pakje uitpakken.", "Heb je het al uitgepakt?"),
     ("iets open pakken", "de doos open maken")),
    ("nlc-inpakken", "iets inpakken", "D", "mid", "打包 / 包起来",
     "你要把礼物包好。",
     ("Zal ik het inpakken?", "Ik moet mijn koffer nog inpakken."),
     ("iets in doen pakken", "iets wikkelen maken")),
    ("nlc-omdraaien", "iets omdraaien", "D", "mid", "把东西翻过来",
     "你让人把纸翻到背面。",
     ("Draai het blad even om.", "Hij draaide zich om."),
     ("iets om keren", "iets achterste voor doen")),
    ("nlc-vastpakken", "iets vastpakken", "D", "mid", "抓住 / 握紧",
     "你让人抓稳扶手。",
     ("Pak de leuning goed vast.", "Hij pakte mijn arm vast."),
     ("iets grijpen vast", "iets houden sterk")),
    ("nlc-duwen", "duwen", "D", "core", "推(门上的标识)",
     "门上写着推。",
     ("Duwen, niet trekken.", "Je moet duwen."),
     ("pushen", "drukken op deur")),
    ("nlc-trekken", "trekken", "D", "core", "拉(门上的标识)",
     "门上写着拉。",
     ("Trekken, niet duwen.", "Je moet aan de deur trekken."),
     ("pullen", "halen de deur")),
    ("nlc-snijden", "iets snijden", "D", "core", "切(用刀)",
     "你要把面包切开。",
     ("Ik snijd het brood.", "Pas op, snijd je niet."),
     ("iets cutten", "iets kapot maken mes")),
    ("nlc-schillen", "iets schillen", "D", "mid", "削皮",
     "你要把土豆削皮。",
     ("Ik schil de aardappels.", "Kun je dit even schillen?"),
     ("de schil af snijden", "huid weg doen")),
    ("nlc-roeren", "roeren", "D", "mid", "搅拌",
     "锅里的东西要不停搅。",
     ("Blijf roeren.", "Roer het goed door."),
     ("mengen maken", "ronddraaien in pan")),
    ("nlc-afdrogen", "afdrogen", "D", "mid", "擦干",
     "洗完碗要擦干。",
     ("Kun je de borden afdrogen?", "Droog je handen af."),
     ("droog maken wrijven", "water weg vegen")),

    # ── 补充:身体与感受 ──────────────────────────────────────────────────────
    ("nlc-honger-hebben", "honger hebben", "E", "core", "饿了",
     "你说你饿了想吃点东西。",
     ("Ik heb honger.", "Heb je al honger?"),
     ("hongerig zijn voelen", "honger voelen krijgen")),
    ("nlc-dorst-hebben", "dorst hebben", "E", "core", "渴了",
     "你说你想喝点水。",
     ("Ik heb dorst.", "Heb je dorst?"),
     ("dorstig voelen", "water willen hebben")),
    ("nlc-het-koud-hebben", "het koud hebben", "E", "core", "觉得冷",
     "你冷得发抖。",
     ("Ik heb het koud.", "Heb je het koud?"),
     ("koud zijn ik", "kou voelen hebben")),
    ("nlc-moe-zijn", "moe zijn", "E", "core", "累了",
     "你今天很累想早点睡。",
     ("Ik ben moe.", "Je ziet er moe uit."),
     ("moeheid hebben", "vermoeid voelen zijn")),
    ("nlc-slaap-hebben", "slaap hebben", "E", "mid", "困了",
     "你眼皮都睁不开了。",
     ("Ik heb slaap.", "Heb je slaap?"),
     ("slaperig zijn voelen", "willen slapen hebben")),
    ("nlc-zin-hebben-in", "zin hebben in", "E", "mid", "想要 / 有兴致做某事",
     "你说你想喝杯咖啡。",
     ("Ik heb zin in koffie.", "Heb je zin om mee te gaan?"),
     ("lust hebben naar", "willen graag doen")),
    ("nlc-gelijk-hebben", "gelijk hebben", "E", "mid", "说得对 / 有道理",
     "你要承认对方说得没错。",
     ("Je hebt gelijk.", "Daar heb je gelijk in."),
     ("juist zijn hebben", "waar hebben")),
    ("nlc-last-hebben-van", "last hebben van", "E", "high", "被……困扰 / 受不了",
     "你要说噪音让你受不了。",
     ("Ik heb last van de buren.", "Heb je last van je rug?"),
     ("problemen hebben met", "gestoord worden door")),
)


def _translate(examples: tuple[str, ...]) -> tuple[str, ...]:
    return tuple(EXAMPLE_MEANINGS.get(e, "") for e in examples)


def _phrases() -> list[Pattern]:
    """省略号就是分界:要填空的是句型,不含的本身就是一句完整的话。

    和英语用同一条规则,所以不必手工标注,也不会出现 ``Mag ik …?`` 被归成
    "整句"这种事——它明明还缺半句。
    """
    return [
        Pattern(id=i, frame=f, group=g, level=lv, meaning=m, cue=c,
                examples=tuple(e), example_meanings=_translate(e), lang="nl",
                track="frame" if "…" in f else "oneliner",
                group_label=_PHRASE_GROUPS[g])
        for i, f, g, lv, m, c, e in _RAW_PHRASES
    ]


def _collocations() -> list[Pattern]:
    return [
        Pattern(id=i, frame=f, group=g, level=lv, meaning=m, cue=c,
                examples=tuple(e), example_meanings=_translate(e), lang="nl",
                track="collocation", wrong=tuple(w), group_label=_SCENE_GROUPS[g])
        for i, f, g, lv, m, c, e, w in _RAW_COLLOCATIONS
    ]


DUTCH = build_catalog("nl", "荷兰语", ("frame", "oneliner", "collocation"),
                      _phrases() + _collocations())
