"""荷兰语例句的中文翻译。

零基础阶段,看不懂的例句等于没有例句——句型本身有释义,但例句是它在真实
句子里长什么样,不给翻译就只是一串字母。

键是例句原文。漏译会被 ``test_every_dutch_example_is_translated`` 抓到,
所以不会出现"有的有、有的没有"。
"""

from __future__ import annotations

EXAMPLE_MEANINGS: dict[str, str] = {
    'Goedemorgen! Alles goed?': '早上好!一切都好吧?',
    'Goedemorgen, meneer.': '早上好,先生。',
    'Hé, hoe gaat het?': '嘿,最近怎么样?',
    'Hoe gaat het met je?': '你最近过得怎么样?',
    '"Hoe gaat het?" "Goed, en met jou?"': '「你好吗?」「挺好的,你呢?」',
    'Prima, en met jou?': '很好,你呢?',
    'Hier, alsjeblieft.': '给你。',
    'Mag ik de rekening, alsjeblieft?': '麻烦结账好吗?',
    'Dank je wel voor je hulp.': '谢谢你的帮忙。',
    'Dank u wel, meneer.': '谢谢您,先生。',
    '"Dank je wel!" "Graag gedaan."': '「谢谢!」「不客气。」',
    'Geen dank, graag gedaan.': '不用谢,应该的。',
    'Tot ziens, fijne dag!': '再见,祝你今天愉快!',
    'Tot ziens en bedankt.': '再见,谢谢。',
    'Tot morgen!': '明天见!',
    'Oké, tot morgen dan.': '好,那明天见。',
    'Bedankt, fijne dag nog!': '谢谢,祝你今天愉快!',
    'Fijn weekend nog!': '周末愉快!',
    'Sorry hoor, ik zag je niet.': '不好意思,我没看见你。',
    'Sorry, dat was mijn fout.': '抱歉,是我的错。',
    'Mag ik een koffie, alsjeblieft?': '请给我一杯咖啡好吗?',
    'Mag ik even kijken?': '我能看一下吗?',
    'Ik wil graag twee broodjes.': '我想要两个三明治。',
    'Ik wil graag betalen.': '我想结账。',
    'Wat kost dit?': '这个多少钱?',
    'Wat kosten deze?': '这些多少钱?',
    'De rekening graag.': '请结账。',
    'Kan ik hier pinnen?': '这里能刷卡吗?',
    'Pinnen mag altijd.': '随时都可以刷卡。',
    'Een moment, ik pak het even.': '稍等,我去拿一下。',
    'Momentje!': '稍等一下!',
    '"Is dat alles?" "Ja, dat is alles."': '「就这些吗?」「是的,就这些。」',
    'Verder nog iets?': '还需要别的吗?',
    'Dank je, ik kijk even rond.': '谢谢,我先随便看看。',
    'Ik kijk alleen even.': '我只是看看。',
    'Waar is het station?': '火车站在哪里?',
    'Waar is de wc?': '洗手间在哪里?',
    'Hoe kom ik bij het centraal station?': '我怎么去中央车站?',
    'Hoe kom ik daar het snelst?': '怎么去那儿最快?',
    'Rechtdoor en dan rechts.': '直走然后右转。',
    'Ga rechtdoor tot het kruispunt.': '一直走到十字路口。',
    'Hoe ver is het lopen?': '走过去有多远?',
    'Is het ver hiervandaan?': '离这儿远吗?',
    'Welk spoor is het?': '是几号站台?',
    'Spoor vijf, geloof ik.': '我记得是五号站台。',
    'Hoe laat vertrekt de trein?': '火车几点开?',
    'Hoe laat begint het?': '几点开始?',
    'Sorry, ik ben verdwaald.': '不好意思,我迷路了。',
    'We zijn een beetje verdwaald.': '我们有点迷路了。',
    'Sorry, kun je dat herhalen?': '抱歉,你能再说一遍吗?',
    'Kunt u dat herhalen, alstublieft?': '请您再说一遍好吗?',
    'Sorry, kun je wat langzamer praten?': '抱歉,你能说慢一点吗?',
    'Iets langzamer, alsjeblieft.': '请稍微慢一点。',
    'Sorry, ik begrijp het niet.': '抱歉,我没听懂。',
    'Ik begrijp het nu wel.': '我现在懂了。',
    'Wat betekent dat woord?': '那个词是什么意思?',
    'Wat betekent "gezellig"?': '「gezellig」是什么意思?',
    'Sorry, spreekt u Engels?': '不好意思,您会说英语吗?',
    'Spreek je Engels?': '你会说英语吗?',
    'Sorry, ik leer het nog.': '抱歉,我还在学。',
    'Mijn Nederlands is nog niet zo goed.': '我的荷兰语还不太好。',
    'Hoe zeg je dat in het Nederlands?': '这个用荷兰语怎么说?',
    'Hoe schrijf je dat?': '这个怎么写?',
    'Kun je me even helpen?': '你能帮我一下吗?',
    'Kunt u mij helpen, alstublieft?': '请您帮我一下好吗?',
    'Zullen we koffie drinken?': '我们去喝杯咖啡吧?',
    'Zullen we gaan?': '我们走吧?',
    'Heb je morgen tijd?': '你明天有空吗?',
    'Heb je even tijd?': '你有空吗?就一会儿。',
    'Sorry, het komt me niet uit.': '抱歉,这个时间我不方便。',
    'Vrijdag komt me beter uit.': '周五对我更方便。',
    'Oké, tot dan!': '好,到时候见!',
    'Prima, tot dan.': '好的,到时候见。',
    'Sorry, ik ben wat later.': '抱歉,我会晚一点到。',
    'Ik ben tien minuten later.': '我会晚十分钟。',
    '"Je woont in Amsterdam?" "Dat klopt."': '「你住在阿姆斯特丹?」「没错。」',
    'Dat klopt niet.': '这不对。',
    '"Sorry!" "Geen probleem."': '「抱歉!」「没事。」',
    'Dat is geen probleem.': '这没问题。',
    '"Zullen we om zeven uur?" "Prima!"': '「我们七点吧?」「可以!」',
    'Dat is prima.': '这样挺好。',
    'Sorry, ik weet het niet.': '抱歉,我不知道。',
    'Ik weet het echt niet.': '我真的不知道。',
    'Misschien, ik laat het weten.': '也许吧,我回头告诉你。',
    'Misschien morgen.': '也许明天。',
    'Dat hangt ervan af hoe laat het is.': '那要看几点。',
    'Dat hangt van het weer af.': '那要看天气。',
    '"Komt hij ook?" "Ik denk het wel."': '「他也来吗?」「我觉得会。」',
    'Ik denk het niet.': '我觉得不会。',
    'Wat jammer dat je niet kunt.': '你来不了太可惜了。',
    'Jammer, volgende keer dan.': '可惜,那下次吧。',
    'Wat gezellig!': '气氛真好!',
    'Het was heel gezellig, bedankt.': '今天很尽兴,谢谢。',
    '"Nog een biertje?" "Doe maar."': '「再来一杯啤酒?」「来吧。」',
    'Doe maar twee.': '来两份吧。',
    'Laat maar, het is niet belangrijk.': '算了,不重要。',
    'Laat maar zitten.': '算了,别管了。',
    '"Sorry, ik was het vergeten." "Het geeft niet."': '「抱歉,我忘了。」「没关系。」',
    'Geeft niks hoor.': '真的没关系。',
    'Ik zoek een kado voor mijn moeder.': '我在给我妈找一件礼物。',
    'Ik zoek de uitgang.': '我在找出口。',
    'Heeft u dit in maat 42?': '这个有 42 码的吗?',
    'Heeft u ook koffie zonder suiker?': '你们有不加糖的咖啡吗?',
    'Ik heb een nieuwe fiets nodig.': '我需要一辆新自行车。',
    'Ik heb meer tijd nodig.': '我需要更多时间。',
    'Kan ik hier parkeren?': '我能在这儿停车吗?',
    'Kan ik dit ruilen?': '这个可以换吗?',
    'Zou je me kunnen helpen?': '你能帮我一下吗?',
    'Zou je dat kunnen herhalen?': '你能再说一遍吗?',
    'Mag ik vragen hoe oud je bent?': '我可以问一下你多大了吗?',
    'Mag ik vragen waarom?': '我可以问一下为什么吗?',
    'Ik denk dat het gaat regenen.': '我觉得要下雨了。',
    'Ik denk dat hij gelijk heeft.': '我觉得他说得对。',
    'Ik vind dit heel leuk.': '我很喜欢这个。',
    'Ik vind hem aardig.': '我觉得他人不错。',
    'Ik hou van koffie.': '我很爱喝咖啡。',
    'Ik hou niet van kou.': '我不喜欢冷。',
    'Ik moet nu gaan.': '我得走了。',
    'Ik moet nog werken.': '我还得工作。',
    'Ik ga naar huis.': '我要回家了。',
    'Ik ga even boodschappen doen.': '我去买点东西。',
    'Ik wil liever thuisblijven.': '我更想待在家里。',
    'Ik drink liever thee.': '我更想喝茶。',
    'Heb je zin om koffie te drinken?': '你想去喝杯咖啡吗?',
    'Heb je zin in een film?': '你想看场电影吗?',
    'Wat voor muziek luister je?': '你听什么样的音乐?',
    'Wat voor werk doe je?': '你做什么工作?',
    'Hoeveel kost het?': '这个多少钱?',
    'Hoeveel mensen komen er?': '有多少人来?',
    'Wanneer begint het?': '什么时候开始?',
    'Wanneer ben je terug?': '你什么时候回来?',
    'Waarom is het dicht?': '为什么关门了?',
    'Waarom niet?': '为什么不呢?',
    'Weet je of de winkel open is?': '你知道这家店开着吗?',
    'Weet je of hij komt?': '你知道他来不来吗?',
    'Het is te duur.': '太贵了。',
    'Het is te koud buiten.': '外面太冷了。',
    'Er is een supermarkt om de hoek.': '拐角有家超市。',
    'Er zijn geen plaatsen meer.': '没有位子了。',
    'Ik ben aan het koken.': '我正在做饭。',
    'Hij is aan het werken.': '他正在工作。',
    'Zal ik je helpen?': '要我帮你吗?',
    'Zal ik even bellen?': '要我打个电话吗?',
    'Hallo, alles goed?': '你好,一切都好吧?',
    'Hallo daar!': '嘿,你好!',
    'Hoi, lang niet gezien!': '嗨,好久不见!',
    'Hoi, hoe is het?': '嗨,最近怎么样?',
    'Goedemiddag, mevrouw.': '下午好,女士。',
    'Goedemiddag allemaal.': '大家下午好。',
    'Goedenavond, welkom.': '晚上好,欢迎。',
    'Goedenavond samen.': '各位晚上好。',
    'Welterusten, slaap lekker.': '晚安,好好睡。',
    'Welterusten allemaal.': '大家晚安。',
    'Tot straks!': '一会儿见!',
    'Oké, tot straks dan.': '好,那一会儿见。',
    'Fijn weekend, tot maandag!': '周末愉快,周一见!',
    'Jij ook een fijn weekend.': '也祝你周末愉快。',
    'Aangenaam kennis te maken.': '很高兴认识你。',
    'Aangenaam, ik ben Liang.': '幸会,我叫 Liang。',
    'Pardon? Wat zei je?': '什么?你刚说什么?',
    'Pardon, mag ik erlangs?': '不好意思,借过一下?',
    'Sorry, mag ik er even langs?': '抱歉,我能过一下吗?',
    'Mag ik erlangs, alstublieft?': '请让我过一下好吗?',
    'Bedankt voor alles!': '谢谢你所做的一切!',
    'Alvast bedankt.': '先谢谢你了。',
    '"Bedankt!" "Geen dank."': '「谢了!」「不用谢。」',
    'Geen dank, hoor.': '真的不用谢。',
    'Eet smakelijk!': '慢用!',
    'Smakelijk eten!': '吃好喝好!',
    'Proost, op jou!': '干杯,敬你!',
    'Proost allemaal!': '大家干杯!',
    'Dat was echt lekker.': '真的很好吃。',
    'Het smaakt lekker.': '味道很好。',
    'Nog een biertje, alsjeblieft.': '请再来一杯啤酒。',
    'Mag ik er nog een?': '我能再要一个吗?',
    '"Voor hier of om mee te nemen?" "Om mee te nemen."': '「堂食还是带走?」「带走。」',
    'Om mee te nemen, graag.': '麻烦打包带走。',
    'Kunnen we apart betalen?': '我们能分开付吗?',
    'Samen of apart?': '一起付还是分开付?',
    'Waar kan ik de melk vinden?': '牛奶在哪儿?',
    'Waar kan ik een pinautomaat vinden?': '哪里有取款机?',
    'Is het ver lopen vanaf hier?': '从这儿走过去远吗?',
    'Nee, vijf minuten.': '不远,五分钟。',
    'Welke bus moet ik nemen naar het centrum?': '去市中心我该坐哪路公交?',
    'Welke tram gaat erheen?': '哪路电车去那儿?',
    'Moet ik overstappen?': '我需要换乘吗?',
    'Je moet overstappen in Utrecht.': '你要在乌得勒支换乘。',
    'Is deze plek vrij?': '这个位子有人吗?',
    'Ja hoor, ga je gang.': '没人,请坐。',
    'Ga je gang!': '你请便!',
    'Gaat uw gang, mevrouw.': '您先请,女士。',
    'Sorry dat ik stoor, heb je even?': '抱歉打扰,你有空吗?',
    'Sorry dat ik stoor.': '不好意思打扰了。',
    'Sorry, wat zei je?': '抱歉,你刚说什么?',
    'Wat zei u, mevrouw?': '您刚说什么,女士?',
    'Sorry, ik versta je niet.': '抱歉,我听不清你说的。',
    'Ik verstond het niet goed.': '我刚才没听清。',
    'Kun je het even opschrijven?': '你能写下来吗?',
    'Schrijf het maar op.': '你写下来吧。',
    'Geen haast hoor.': '真的不着急。',
    'Er is geen haast bij.': '这件事不急。',
    'Schikt het om drie uur?': '三点方便吗?',
    'Als het schikt.': '如果方便的话。',
    'Ik kan helaas niet, sorry.': '我恐怕去不了,抱歉。',
    'Helaas kan ik niet komen.': '很遗憾我来不了。',
    'Jammer, volgende keer!': '可惜,下次吧!',
    'Volgende keer zeker.': '下次一定。',
    '"Mag ik even?" "Natuurlijk!"': '「我能用一下吗?」「当然!」',
    'Natuurlijk niet.': '当然不是。',
    '"Kom je ook?" "Zeker weten!"': '「你也来吗?」「那还用说!」',
    'Weet je het zeker?': '你确定吗?',
    'Daar ben ik het helemaal mee eens.': '这点我完全同意。',
    'Mee eens!': '同意!',
    '"Is het druk?" "Nee, dat valt mee."': '「人多吗?」「还好,没想象中那么多。」',
    'Dat viel me mee.': '比我想的要好。',
    'Het weer valt tegen.': '天气不如预期。',
    'Dat viel me tegen.': '比我想的要差。',
    '"Hoe laat komt hij?" "Geen idee."': '「他几点来?」「完全不知道。」',
    'Echt geen idee.': '真的一点头绪都没有。',
    'Het maakt mij niet uit.': '我都行。',
    'Maakt niet uit.': '无所谓。',
    'Wat leuk voor je!': '真替你高兴!',
    'Wat leuk om te horen.': '听到这个真好。',
    'Succes morgen!': '明天加油!',
    'Veel succes!': '祝你顺利!',
    'Beterschap, hoor!': '早日康复啊!',
    'Veel beterschap.': '祝早日康复。',
    'Gefeliciteerd met je verjaardag!': '生日快乐!',
    'Gefeliciteerd!': '恭喜!',
    'Hé, lang niet gezien!': '嘿,好久不见!',
    'Lang niet gezien, hoe gaat het?': '好久不见,最近怎么样?',
    'Doe de groeten aan je vrouw.': '代我向你太太问好。',
    'Doe de groeten thuis!': '代我向家里问好!',
    'Wat een weer, zeg!': '这什么鬼天气啊!',
    'Lekker weertje vandaag.': '今天天气真不错。',
    'Het is heel druk vandaag.': '今天人特别多。',
    'Ik heb het druk.': '我很忙。',
    'Ik ben ziek, ik kom niet.': '我病了,就不去了。',
    'Hij is al een week ziek.': '他已经病了一周了。',
    'Ik heb pijn in mijn rug.': '我背疼。',
    'Ik heb keelpijn.': '我嗓子疼。',
    'Ik voel me niet zo goed.': '我有点不舒服。',
    'Voel je je beter?': '你好点了吗?',
    'Ik wil graag een afspraak met de huisarts.': '我想约家庭医生。',
    'Heeft u een huisarts?': '您有家庭医生吗?',
    'Waar is de dichtstbijzijnde apotheek?': '最近的药店在哪儿?',
    'De apotheek is om de hoek.': '药店就在拐角。',
    'Is dit zonder recept te krijgen?': '这个不用处方能买吗?',
    'Daar heb je een recept voor nodig.': '那个需要处方。',
    'Ik woon in Amsterdam.': '我住在阿姆斯特丹。',
    'Waar woon je?': '你住在哪儿?',
    'Ik kom uit China.': '我来自中国。',
    'Waar kom je vandaan?': '你是哪里人?',
    'Ik werk bij een bank.': '我在一家银行工作。',
    'Waar werk je?': '你在哪儿工作?',
    'Ik leer Nederlands sinds een jaar.': '我学荷兰语一年了。',
    'Hoe lang leer je al Nederlands?': '你学荷兰语多久了?',
    'Ik moet nog boodschappen doen.': '我还得去买菜。',
    'Zullen we samen boodschappen doen?': '我们一起去买菜吧?',
    'Zal ik koffie zetten?': '要我煮咖啡吗?',
    'Hij zet elke ochtend koffie.': '他每天早上煮咖啡。',
    'Ik doe de afwas wel.': '我来洗碗吧。',
    'Wie doet vandaag de afwas?': '今天谁洗碗?',
    'Ik moet de was nog doen.': '我还得洗衣服。',
    'De was hangt buiten.': '衣服晾在外面。',
    'Kun je even opruimen?': '你能收拾一下吗?',
    'Ik heb de kamer opgeruimd.': '我把房间收拾好了。',
    'Doe het licht even aan.': '把灯打开一下。',
    'Vergeet niet het licht uit te doen.': '别忘了关灯。',
    'Doe de deur even dicht.': '把门带上。',
    'De deur staat open.': '门开着。',
    'Ik ga naar bed.': '我去睡了。',
    'Hij gaat altijd laat naar bed.': '他总是很晚才睡。',
    'Ik neem de trein naar Utrecht.': '我坐火车去乌得勒支。',
    'Neem je de trein of de bus?': '你坐火车还是公交?',
    'Ik ga op de fiets.': '我骑车去。',
    'Zullen we op de fiets gaan?': '我们骑车去吧?',
    'Ik wil een afspraak maken.': '我想预约一下。',
    'We hebben een afspraak om drie uur.': '我们约了三点。',
    'Ik moet even geld pinnen.': '我得去取点钱。',
    'Kun je hier geld pinnen?': '这里能取钱吗?',
    'Je moet dit formulier invullen.': '你得填这张表。',
    'Heb je het formulier al ingevuld?': '你表填好了吗?',
    'De huur moet voor de eerste betaald zijn.': '房租要在一号前交。',
    'Ik heb de huur al betaald.': '我已经交过房租了。',
    'Mag ik een vraag stellen?': '我可以提个问题吗?',
    'Hij stelde een goede vraag.': '他问了个好问题。',
    'Besteed aandacht aan de details.': '注意细节。',
    'Hij besteedt er geen aandacht aan.': '他根本不留意这件事。',
    'Ik heb een fout gemaakt.': '我犯了个错。',
    'Iedereen maakt fouten.': '谁都会犯错。',
    'Hij komt zijn afspraken altijd na.': '他答应的事总能做到。',
    'Kom je afspraken na.': '说到就要做到。',
    'Zullen we een pauze nemen?': '我们休息一下吧?',
    'Ik neem even pauze.': '我歇一会儿。',
    'Kun jij de deur opendoen?': '你能去开下门吗?',
    'Ik doe wel open.': '我去开门。',
    'Kun je dat even oppakken?': '你能把那个捡起来吗?',
    'Hij pakte het van de grond op.': '他把它从地上捡了起来。',
    'Kun je dit even vasthouden?': '你能帮我拿一下吗?',
    'Hou het goed vast.': '抓稳了。',
    'Ik liet mijn telefoon vallen.': '我把手机摔了。',
    'Pas op, niet laten vallen!': '小心,别摔了!',
    'Gooi het maar weg.': '扔了吧。',
    'Niet weggooien, ik heb het nog nodig.': '别扔,我还要用。',
    'Zet de tv even aan.': '把电视打开。',
    'De verwarming staat aan.': '暖气开着。',
    'Ik schrijf het even op.': '我记一下。',
    'Schrijf het op, anders vergeet je het.': '写下来吧,不然你会忘。',
    'Doe het licht uit.': '把灯关了。',
    'Doe je jas maar uit.': '把外套脱了吧。',
    'Ik kook vanavond.': '今晚我做饭。',
    'Hij kookt elke dag.': '他每天做饭。',
    'Kun je de tafel dekken?': '你能摆一下餐具吗?',
    'De tafel is gedekt.': '餐桌已经摆好了。',
    'Ik ga even stofzuigen.': '我去吸一下地。',
    'Heb je al gestofzuigd?': '你吸过地了吗?',
    'Vergeet de vuilnis niet buiten te zetten.': '别忘了把垃圾拿出去。',
    'Ik zet de vuilnis buiten.': '我去把垃圾放外面。',
    'Kun je de planten water geven?': '你能给花浇下水吗?',
    'Ik heb ze al water gegeven.': '我已经浇过了。',
    'Doe je de gordijnen dicht?': '你把窗帘拉上好吗?',
    'De gordijnen zijn open.': '窗帘开着。',
    'Zet de verwarming even aan.': '把暖气开一下。',
    'De verwarming staat uit.': '暖气关着。',
    'Ik ga even douchen.': '我去冲个澡。',
    'Hij neemt elke ochtend een douche.': '他每天早上洗澡。',
    'Heb je je tanden gepoetst?': '你刷牙了吗?',
    'Ik poets twee keer per dag mijn tanden.': '我一天刷两次牙。',
    'Ik hang de was even op.': '我去把衣服晾上。',
    'Ik moet nog een kaartje kopen.': '我还得买张票。',
    'Waar kan ik een kaartje kopen?': '哪里能买票?',
    'Vergeet niet in te checken.': '别忘了刷卡进站。',
    'Ik ben vergeten uit te checken.': '我忘了刷卡出站。',
    'Ik ga even de weg vragen.': '我去问下路。',
    'Hij vroeg mij de weg.': '他向我问路。',
    'Ik moet nog een pakje ophalen.': '我还得去取个快递。',
    'Het pakje ligt bij de buren.': '包裹在邻居那儿。',
    'Ik wil een rekening openen.': '我想开个账户。',
    'Hij heeft een rekening geopend.': '他开了个账户。',
    'Je moet je inschrijven bij de gemeente.': '你得去市政厅登记。',
    'Ik heb me ingeschreven voor de cursus.': '我报了那门课。',
    'Ik moet de afspraak afzeggen.': '我得取消预约。',
    'Hij heeft afgezegd.': '他取消了。',
    'Je moet in de rij staan.': '你得排队。',
    'We stonden een half uur in de rij.': '我们排了半小时队。',
    'Ik stuur je een mail.': '我发封邮件给你。',
    'Heb je de mail gestuurd?': '邮件发了吗?',
    'Ik heb vanmiddag een vergadering.': '我下午有个会。',
    'De vergadering duurde twee uur.': '会开了两个小时。',
    'Ik moet een presentatie geven.': '我得做个汇报。',
    'Zij gaf een goede presentatie.': '她那个汇报做得很好。',
    'Ik maak even aantekeningen.': '我记一下笔记。',
    'Hij maakt nooit aantekeningen.': '他从不记笔记。',
    'Ik moet nog huiswerk maken.': '我还得写作业。',
    'Heb je je huiswerk af?': '你作业写完了吗?',
    'Ik volg een cursus Nederlands.': '我在上荷兰语课。',
    'Hij volgt een avondcursus.': '他在上夜校。',
    'Ik doe volgende week examen.': '我下周考试。',
    'Hij is geslaagd voor zijn examen.': '他考试通过了。',
    'Ik neem volgende week verlof op.': '我下周请假。',
    'Hoeveel verlof heb je nog?': '你还剩多少假?',
    'Druk op de groene knop.': '按绿色那个按钮。',
    'Je moet hier drukken.': '你得按这里。',
    'Draai de kraan dicht.': '把水龙头关上。',
    'De kraan lekt.': '水龙头在漏水。',
    'Ik ga het pakje uitpakken.': '我去把包裹拆开。',
    'Heb je het al uitgepakt?': '你拆开了吗?',
    'Zal ik het inpakken?': '要我包起来吗?',
    'Ik moet mijn koffer nog inpakken.': '我还得收拾行李。',
    'Draai het blad even om.': '把那页翻过来。',
    'Hij draaide zich om.': '他转过身来。',
    'Pak de leuning goed vast.': '抓稳扶手。',
    'Hij pakte mijn arm vast.': '他抓住了我的胳膊。',
    'Duwen, niet trekken.': '推,不是拉。',
    'Je moet duwen.': '你得推。',
    'Trekken, niet duwen.': '拉,不是推。',
    'Je moet aan de deur trekken.': '你得拉门。',
    'Ik snijd het brood.': '我来切面包。',
    'Pas op, snijd je niet.': '小心,别切到手。',
    'Ik schil de aardappels.': '我来削土豆皮。',
    'Kun je dit even schillen?': '你能把这个削一下皮吗?',
    'Blijf roeren.': '一直搅。',
    'Roer het goed door.': '好好搅匀。',
    'Kun je de borden afdrogen?': '你能把碗擦干吗?',
    'Droog je handen af.': '把手擦干。',
    'Ik heb honger.': '我饿了。',
    'Heb je al honger?': '你饿了吗?',
    'Ik heb dorst.': '我渴了。',
    'Heb je dorst?': '你渴吗?',
    'Ik heb het koud.': '我觉得冷。',
    'Heb je het koud?': '你冷吗?',
    'Ik ben moe.': '我累了。',
    'Je ziet er moe uit.': '你看起来很累。',
    'Ik heb slaap.': '我困了。',
    'Heb je slaap?': '你困吗?',
    'Ik heb zin in koffie.': '我想喝杯咖啡。',
    'Heb je zin om mee te gaan?': '你想一起去吗?',
    'Je hebt gelijk.': '你说得对。',
    'Daar heb je gelijk in.': '这点你说得对。',
    'Ik heb last van de buren.': '邻居吵得我受不了。',
    'Heb je last van je rug?': '你背不舒服吗?',
}
