"""动词 + 名词的固定搭配(词块)。

和句型并列的另一条训练线。两者的失败方式完全不同:

* 句型用错不会出语法错误,只是话接不顺;
* 搭配用错**语法完全正确,但一听就不是母语者**——"open the light"
  "do a decision""eat medicine" 全都合语法,也全都不是英语。

所以每条都带一个 ``wrong``:中式英语的直译版。测验用它当干扰项,打的正是
"逐词翻译"这个习惯本身——错一次的印象远比读十遍正确答案深。

分组沿用"按场景检索"的思路,而不是按动词归类:真实对话里你是先想到要说
什么事,再去取词,不会先想到"我要用 make"。

中文情境与释义里不出现任何拉丁字母——问句一旦泄题,就直接指向某个选项了。
"""

from __future__ import annotations

#: (id, 搭配, 分组, 难度, 释义, 情境, 例句, 中式英语错误版)
_RAW_COLLOCATIONS: tuple[tuple, ...] = (
    # ── A 日常起居 ────────────────────────────────────────────────────────────
    ("coll-turn-on-light", "turn on the light", "A", "core", "开灯",
     "你进屋发现太暗了,让别人把灯打开。",
     ("Can you turn on the light?", "Don't forget to turn off the lights."),
     ("open the light", "open the lamp")),
    ("coll-take-medicine", "take medicine", "A", "core", "吃药",
     "你要提醒别人按时服药。",
     ("Did you take your medicine this morning?", "I have to take it twice a day."),
     ("eat medicine", "drink medicine")),
    ("coll-take-shower", "take a shower", "A", "core", "洗澡(淋浴)",
     "你说你先去冲个澡再出门。",
     ("I'll take a quick shower first.", "He takes a shower every morning."),
     ("wash a shower", "do a shower")),
    ("coll-do-dishes", "do the dishes", "A", "core", "洗碗",
     "你说饭后由你来收拾碗筷。",
     ("I'll do the dishes tonight.", "Whoever cooks doesn't do the dishes."),
     ("wash the dishes clean", "make the dishes")),
    ("coll-make-bed", "make the bed", "A", "core", "整理床铺",
     "你说早上起来要先把床铺好。",
     ("I make the bed before I leave.", "She never makes her bed."),
     ("clean the bed", "tidy the bed")),
    ("coll-take-photo", "take a photo", "A", "core", "拍照",
     "你想请路人帮你们拍一张。",
     ("Could you take a photo of us?", "I took a few photos on the way."),
     ("make a photo", "shoot a photo")),
    ("coll-do-laundry", "do the laundry", "A", "core", "洗衣服",
     "你说这周末得把衣服洗了。",
     ("I need to do the laundry this weekend.", "He does his own laundry."),
     ("wash the laundry", "make the laundry")),
    ("coll-set-alarm", "set an alarm", "A", "core", "定闹钟",
     "你说明早要早起,得定个闹钟。",
     ("I set an alarm for six.", "Did you set an alarm?"),
     ("make an alarm", "fix an alarm")),
    ("coll-run-errands", "run errands", "A", "mid", "跑腿办杂事",
     "你说下午要出去办几件琐碎的事。",
     ("I've got some errands to run this afternoon.", "She was out running errands."),
     ("do errands around", "make errands")),
    ("coll-grab-a-bite", "grab a bite", "A", "mid", "随便吃点东西",
     "你提议先简单吃点再继续。",
     ("Let's grab a bite before the movie.", "I'll grab a bite on the way."),
     ("eat a bite", "take a bite of food")),

    # ── B 时间与安排 ──────────────────────────────────────────────────────────
    ("coll-take-day-off", "take a day off", "B", "core", "请一天假",
     "你要说下周二你不上班。",
     ("I'm taking Tuesday off.", "He took a day off to move house."),
     ("ask for a holiday", "have a vacation day")),
    ("coll-make-appointment", "make an appointment", "B", "core", "预约(看医生、办事)",
     "你要说你已经跟牙医约好了时间。",
     ("I made an appointment with the dentist.", "You'll need to make an appointment."),
     ("do an appointment", "book a time with")),
    ("coll-set-up-meeting", "set up a meeting", "B", "core", "安排一场会",
     "你要提议把相关的人约到一起谈。",
     ("Let's set up a meeting next week.", "Can you set something up with them?"),
     ("make a meeting", "open a meeting")),
    ("coll-push-back-meeting", "push back a meeting", "B", "mid", "把会议往后推",
     "你要说那场会改到更晚的时间了。",
     ("We pushed the meeting back to Thursday.", "Can we push it back an hour?"),
     ("delay backward the meeting", "move the meeting after")),
    ("coll-call-off", "call off", "B", "mid", "取消(已安排好的事)",
     "你要说因为天气活动取消了。",
     ("They called off the trip.", "The game was called off."),
     ("cancel off", "close the plan")),
    ("coll-make-time", "make time", "B", "mid", "挤出时间",
     "你要说再忙也会腾出时间来做这件事。",
     ("I'll make time for it.", "You have to make time for exercise."),
     ("spare out time", "give out time")),
    ("coll-run-late", "run late", "B", "core", "要迟到了",
     "你在路上,要跟对方说你会晚一点到。",
     ("Sorry, I'm running late.", "We're running about ten minutes late."),
     ("be late running", "arrive late soon")),
    ("coll-catch-flight", "catch a flight", "B", "core", "赶飞机",
     "你要说你一早要去赶航班。",
     ("I have to catch an early flight.", "We barely caught our flight."),
     ("take up a flight", "sit a flight")),
    ("coll-book-a-table", "book a table", "B", "core", "订餐厅位子",
     "你要说你已经订好了座位。",
     ("I booked a table for seven.", "Should I book a table?"),
     ("order a table", "reserve a seat of restaurant")),
    ("coll-free-up", "free up time", "B", "high", "腾出时间 / 空出档期",
     "你要说推掉一些事之后多出了一段时间。",
     ("That frees up my whole afternoon.", "I freed up some time for it."),
     ("empty out time", "release time")),

    # ── C 工作与协作 ──────────────────────────────────────────────────────────
    ("coll-meet-deadline", "meet a deadline", "C", "core", "按时完成 / 赶上截止时间",
     "你要说这个时间点你能做到。",
     ("We met the deadline.", "There's no way we'll meet that deadline."),
     ("finish the deadline", "catch up the deadline")),
    ("coll-miss-deadline", "miss a deadline", "C", "core", "没赶上截止时间",
     "你要承认这次没按时交。",
     ("We missed the deadline by two days.", "I've never missed a deadline."),
     ("lose the deadline", "exceed the deadline")),
    ("coll-raise-concern", "raise a concern", "C", "mid", "提出顾虑",
     "你要在会上把一个担心正式说出来。",
     ("She raised a few concerns about the timeline.", "Let me raise one concern."),
     ("put a worry", "speak a concern")),
    ("coll-take-the-lead", "take the lead", "C", "mid", "牵头负责",
     "你要说这件事由你来主导。",
     ("I'll take the lead on this one.", "She took the lead after he left."),
     ("take the leader", "do the lead")),
    ("coll-take-responsibility", "take responsibility", "C", "core", "承担责任",
     "你要说这件事错在你,你认。",
     ("I take full responsibility for it.", "Nobody wants to take responsibility."),
     ("undertake the duty", "carry responsibility")),
    ("coll-run-numbers", "run the numbers", "C", "high", "算一算账 / 跑一遍数字",
     "你要说先把成本仔细核算一遍再定。",
     ("Let me run the numbers first.", "Have you run the numbers on this?"),
     ("count the numbers", "calculate the number")),
    ("coll-follow-up", "follow up", "C", "core", "跟进 / 后续再联系",
     "你要说这件事你之后会再去确认。",
     ("I'll follow up with them tomorrow.", "Just following up on my last message."),
     ("follow after", "chase behind")),
    ("coll-keep-posted", "keep someone posted", "C", "mid", "随时告知进展",
     "你要承诺有消息就通知对方。",
     ("I'll keep you posted.", "Keep me posted on how it goes."),
     ("keep someone knowing", "tell someone always")),
    ("coll-loop-in", "loop someone in", "C", "high", "把某人也拉进来同步",
     "你要说这件事应该让另一个人也知道。",
     ("Let me loop her in on this.", "Can you loop me in?"),
     ("pull someone in circle", "add someone to know")),
    ("coll-take-notes", "take notes", "C", "core", "记笔记",
     "你要说开会时你会把要点记下来。",
     ("I'll take notes during the call.", "He never takes notes."),
     ("write down notes", "do notes")),
    ("coll-give-feedback", "give feedback", "C", "core", "给反馈意见",
     "你要请别人看完之后说说想法。",
     ("Could you give me some feedback?", "She gave really useful feedback."),
     ("give opinions back", "make feedback")),
    ("coll-hit-target", "hit a target", "C", "mid", "达成目标",
     "你要说这个季度的指标完成了。",
     ("We hit our target this quarter.", "They missed the target again."),
     ("reach up the target", "arrive the target")),

    # ── D 沟通与社交 ──────────────────────────────────────────────────────────
    ("coll-give-a-call", "give someone a call", "D", "core", "给某人打个电话",
     "你要说你晚点会打电话过去。",
     ("I'll give you a call tonight.", "Give me a call when you're free."),
     ("make someone a phone", "play a call")),
    ("coll-answer-phone", "answer the phone", "D", "core", "接电话",
     "你要说刚才没人接。",
     ("Nobody answered the phone.", "Can you answer it?"),
     ("receive the phone", "take the phone up")),
    ("coll-leave-a-message", "leave a message", "D", "core", "留个口信",
     "对方不在,你要留话。",
     ("Can I leave a message?", "She left a message for you."),
     ("put a message", "keep a message")),
    ("coll-have-a-word", "have a word with", "D", "mid", "找某人私下谈两句",
     "你要说你得单独跟他说一下。",
     ("Can I have a word with you?", "I'll have a word with him about it."),
     ("say a word to", "talk a word with")),
    ("coll-catch-up", "catch up with", "D", "core", "叙旧 / 聊聊近况",
     "你跟老朋友约着见一面聊聊。",
     ("Let's catch up soon.", "I caught up with her last weekend."),
     ("chase up with", "meet and talk old")),
    ("coll-keep-in-touch", "keep in touch", "D", "core", "保持联系",
     "分别时你要说以后常联系。",
     ("Let's keep in touch.", "We've kept in touch over the years."),
     ("keep connection", "hold touch")),
    ("coll-make-small-talk", "make small talk", "D", "mid", "闲聊几句客套话",
     "你要说在电梯里随便聊了两句。",
     ("We made small talk in the lift.", "He's terrible at small talk."),
     ("speak small words", "do small talking")),
    ("coll-break-the-ice", "break the ice", "D", "mid", "打破僵局 / 活跃气氛",
     "场面很尴尬,你要先开口缓和一下。",
     ("He told a joke to break the ice.", "That broke the ice nicely."),
     ("break the cold", "open the ice")),
    ("coll-say-hello", "say hello to", "D", "core", "代为问好",
     "你要托对方向他家人问好。",
     ("Say hello to your parents for me.", "She said hello."),
     ("speak hello to", "greet hello to")),
    ("coll-get-in-touch", "get in touch with", "D", "core", "联系上某人",
     "你要说你一直联系不上他。",
     ("I can't get in touch with him.", "Get in touch when you arrive."),
     ("contact in touch", "touch with")),

    # ── E 想法与决定 ──────────────────────────────────────────────────────────
    ("coll-make-decision", "make a decision", "E", "core", "做决定",
     "你要说这件事得由他自己拿主意。",
     ("It's not an easy decision to make.", "He made the decision on his own."),
     ("do a decision", "take a decision")),
    ("coll-change-mind", "change one's mind", "E", "core", "改变主意",
     "你要说他本来答应了,后来又反悔。",
     ("He changed his mind at the last minute.", "I've changed my mind."),
     ("change the idea", "turn the mind")),
    ("coll-make-up-mind", "make up one's mind", "E", "mid", "拿定主意",
     "你要催对方别再犹豫了。",
     ("Make up your mind!", "I still haven't made up my mind."),
     ("decide up the mind", "fix the mind")),
    ("coll-have-second-thoughts", "have second thoughts", "E", "mid", "开始犹豫 / 重新考虑",
     "你本来定了,现在又有点动摇。",
     ("I'm having second thoughts about it.", "She had second thoughts and pulled out."),
     ("have the second idea", "think the second time")),
    ("coll-make-a-point", "make a point", "E", "mid", "说到一个点子上",
     "你要承认对方刚说的有道理。",
     ("You make a good point.", "He made an important point."),
     ("say a point", "take a point")),
    ("coll-give-it-thought", "give it some thought", "E", "mid", "好好想一想再说",
     "你不想立刻回答,要先考虑。",
     ("Let me give it some thought.", "Give it some thought and let me know."),
     ("think it some", "do some thinking of it")),
    ("coll-weigh-options", "weigh the options", "E", "high", "权衡各种选择",
     "你要说做决定前要把几条路都比一比。",
     ("We need to weigh the options carefully.", "He's still weighing his options."),
     ("compare the choices weight", "measure the options")),
    ("coll-draw-conclusion", "draw a conclusion", "E", "high", "得出结论",
     "你要提醒别人现在下定论还太早。",
     ("It's too early to draw any conclusions.", "What conclusion did you draw?"),
     ("get a conclusion", "make out a conclusion")),

    # ── F 问题与麻烦 ──────────────────────────────────────────────────────────
    ("coll-make-mistake", "make a mistake", "F", "core", "犯错",
     "你要承认这次是你弄错了。",
     ("I made a mistake.", "Everyone makes mistakes."),
     ("do a mistake", "have a mistake")),
    ("coll-stuck-in-traffic", "be stuck in traffic", "F", "core", "堵车堵住了",
     "你迟到了,要解释路上堵得厉害。",
     ("Sorry, I was stuck in traffic.", "We got stuck in traffic for an hour."),
     ("the car is blocked", "meet traffic jam")),
    ("coll-sort-out", "sort out a problem", "F", "mid", "把问题理清解决掉",
     "你要说这件事你会处理好。",
     ("I'll sort it out.", "We need to sort this out today."),
     ("solve out the problem", "arrange the problem")),
    ("coll-cause-trouble", "cause trouble", "F", "core", "惹麻烦",
     "你要说那件事带来了不少麻烦。",
     ("It caused a lot of trouble.", "He's always causing trouble."),
     ("make trouble to happen", "bring troubles out")),
    ("coll-run-into-problem", "run into a problem", "F", "mid", "碰上问题",
     "你要说做到一半遇到了障碍。",
     ("We ran into a problem halfway through.", "If you run into any issues, call me."),
     ("meet a problem on", "hit into a problem")),
    ("coll-take-blame", "take the blame", "F", "mid", "背锅 / 承担过失",
     "你要说这次责任由他扛下来了。",
     ("He took the blame for all of us.", "I'm not taking the blame for this."),
     ("carry the blame", "accept the fault")),
    ("coll-make-up-for", "make up for", "F", "mid", "弥补",
     "你要说会想办法补偿对方。",
     ("I'll make up for it.", "Nothing can make up for lost time."),
     ("compensate up", "repair for")),
    ("coll-let-down", "let someone down", "F", "mid", "让某人失望",
     "你要说你不想辜负他们的期待。",
     ("I don't want to let you down.", "He really let the team down."),
     ("make someone disappointed down", "fall someone down")),

    # ── G 学习与进步 ──────────────────────────────────────────────────────────
    ("coll-make-progress", "make progress", "G", "core", "取得进展",
     "你要说这段时间确实有长进。",
     ("You've made a lot of progress.", "We're making slow progress."),
     ("have progress", "get progress up")),
    ("coll-pick-up-habit", "pick up a habit", "G", "mid", "养成一个习惯",
     "你要说你最近开始每天跑步了。",
     ("I picked up the habit last year.", "He picked up a few bad habits."),
     ("make a habit", "grow a habit")),
    ("coll-break-habit", "break a habit", "G", "mid", "戒掉一个习惯",
     "你要说这个毛病很难改。",
     ("It's a hard habit to break.", "She finally broke the habit."),
     ("quit a habit", "cut a habit")),
    ("coll-get-hang-of", "get the hang of", "G", "mid", "摸到窍门 / 上手",
     "你要说练几次就顺手了。",
     ("You'll get the hang of it.", "It took me a week to get the hang of it."),
     ("catch the trick of", "know the way of")),
    ("coll-pay-attention", "pay attention to", "G", "core", "注意 / 留心",
     "你要提醒对方留意某个细节。",
     ("Pay attention to the details.", "Nobody was paying attention."),
     ("give attention on", "put attention to")),
    ("coll-take-exam", "take an exam", "G", "core", "参加考试",
     "你要说你下周有一场考试。",
     ("I'm taking the exam next week.", "She passed the exam."),
     ("do an exam", "join an exam")),
    ("coll-brush-up-on", "brush up on", "G", "high", "把生疏的东西重新捡起来",
     "你要说出发前得把语言再练一练。",
     ("I need to brush up on my Dutch.", "He brushed up on his maths."),
     ("review up", "pick back up the skill")),
    ("coll-get-point", "get the point", "G", "core", "听懂要点 / 明白意思",
     "你要确认对方是否听明白了。",
     ("I get the point.", "You're missing the point."),
     ("understand the point out", "catch the meaning point")),

    # ── H 身体与状态 ──────────────────────────────────────────────────────────
    ("coll-catch-cold", "catch a cold", "H", "core", "感冒了",
     "你要说昨天受凉了。",
     ("I caught a cold over the weekend.", "Don't catch a cold."),
     ("get a cold illness", "take a cold")),
    ("coll-take-break", "take a break", "H", "core", "休息一下",
     "你要提议先停下来歇会儿。",
     ("Let's take a break.", "You should take a break."),
     ("have a rest break", "do a break")),
    ("coll-get-rest", "get some rest", "H", "core", "好好休息",
     "你要劝对方早点睡。",
     ("You need to get some rest.", "Go home and get some rest."),
     ("take some rest up", "have good rest")),
    ("coll-lose-weight", "lose weight", "H", "core", "减肥",
     "你要说他瘦了不少。",
     ("He's lost a lot of weight.", "I'm trying to lose weight."),
     ("reduce weight down", "decrease fat")),
    ("coll-work-out", "work out", "H", "core", "健身 / 锻炼",
     "你要说你一周去三次健身房。",
     ("I work out three times a week.", "She works out every morning."),
     ("do body exercise out", "make exercise")),
    ("coll-feel-under-weather", "feel under the weather", "H", "high", "身体不太舒服",
     "你要委婉地说今天状态不好。",
     ("I'm feeling a bit under the weather.", "He's been under the weather all week."),
     ("feel bad weather", "be under bad body")),
    ("coll-get-over", "get over", "H", "mid", "从病里或情绪里缓过来",
     "你要说他花了很久才走出来。",
     ("It took her weeks to get over it.", "I've finally got over the flu."),
     ("pass over the illness", "walk out from")),
    ("coll-burn-out", "burn out", "H", "high", "累垮 / 倦怠",
     "你要说再这样下去人会垮掉。",
     ("He burned out after two years.", "I'm close to burning out."),
     ("be tired out burning", "use up the energy")),
    # ── 补充 ──────────────────────────────────────────────────────────────────
    ("coll-pay-bill", "pay a bill", "A", "core", "付账单",
     "你要说这个月的水电费还没交。",
     ("I forgot to pay the bill.", "The bills are paid automatically."),
     ("pay the money of bill", "give the bill")),
    ("coll-take-out-trash", "take out the trash", "A", "core", "倒垃圾",
     "你要说轮到他去倒垃圾了。",
     ("It's your turn to take out the trash.", "I took the trash out already."),
     ("throw the trash out door", "carry the rubbish")),
    ("coll-do-cooking", "do the cooking", "A", "mid", "负责做饭",
     "你要说家里是他在做饭。",
     ("He does most of the cooking.", "I'll do the cooking tonight."),
     ("make the cooking", "cook the meal work")),
    ("coll-charge-phone", "charge a phone", "A", "core", "给手机充电",
     "你要说手机快没电了得充上。",
     ("I need to charge my phone.", "Is it still charging?"),
     ("fill the phone electricity", "add power to phone")),
    ("coll-kill-time", "kill time", "B", "mid", "打发时间",
     "你要说等车的时候随便逛了逛。",
     ("I was just killing time.", "We killed an hour at the café."),
     ("spend time empty", "pass the time away")),
    ("coll-save-time", "save time", "B", "core", "省时间",
     "你要说这样做能快不少。",
     ("That'll save us a lot of time.", "It saves time in the long run."),
     ("economize time", "reduce the time cost")),
    ("coll-waste-time", "waste time", "B", "core", "浪费时间",
     "你要说别在这件事上耗着了。",
     ("Don't waste your time on it.", "We wasted the whole morning."),
     ("cost time uselessly", "lose time")),
    ("coll-put-off", "put off", "B", "mid", "拖延 / 推迟去做",
     "你要说这件事别再往后拖了。",
     ("Stop putting it off.", "They put the decision off again."),
     ("delay to later", "push to behind")),
    ("coll-meet-expectations", "meet expectations", "C", "mid", "达到预期",
     "你要说结果和大家想的差不多。",
     ("It met all our expectations.", "The results fell short of expectations."),
     ("reach the expectation", "satisfy the expect")),
    ("coll-make-an-effort", "make an effort", "C", "core", "下功夫 / 努力一把",
     "你要说至少要试着做做看。",
     ("At least make an effort.", "She made a real effort to help."),
     ("do effort", "pay effort")),
    ("coll-do-favour", "do someone a favour", "C", "core", "帮某人一个忙",
     "你要开口请别人帮个小忙。",
     ("Could you do me a favour?", "He did me a huge favour."),
     ("help someone a favour", "give someone a favour")),
    ("coll-give-a-hand", "give someone a hand", "C", "core", "搭把手",
     "你看到别人搬东西,过去帮忙。",
     ("Let me give you a hand.", "Can you give me a hand with this?"),
     ("help a hand", "lend a help")),
    ("coll-cover-for", "cover for someone", "C", "high", "替某人顶班 / 打掩护",
     "你要说同事休假时由你接手。",
     ("I'm covering for her this week.", "Can you cover for me on Friday?"),
     ("replace for someone", "take place of someone")),
    ("coll-draw-attention", "draw attention to", "D", "mid", "引起注意 / 提请留意",
     "你要让大家注意到报告里的一个数字。",
     ("I'd like to draw your attention to this.", "It drew a lot of attention."),
     ("cause attention", "attract eyes to")),
    ("coll-make-suggestion", "make a suggestion", "D", "core", "提个建议",
     "你要在讨论里提出一个想法。",
     ("Can I make a suggestion?", "She made a few suggestions."),
     ("give a suggestion", "put a suggestion")),
    ("coll-give-advice", "give advice", "D", "core", "给建议",
     "你要说他给了你很有用的意见。",
     ("He gave me some good advice.", "I'm not giving advice, just thinking aloud."),
     ("give an advice", "make advice")),
    ("coll-keep-promise", "keep a promise", "D", "core", "守信 / 说到做到",
     "你要说他答应的事都做到了。",
     ("He always keeps his promises.", "She broke her promise."),
     ("hold the promise", "protect the promise")),
    ("coll-settle-argument", "settle an argument", "D", "high", "了结一场争执",
     "你要说那件事最后谈开了。",
     ("That settles the argument.", "They settled it over coffee."),
     ("solve the quarrel", "finish the argue")),
    ("coll-take-a-chance", "take a chance", "E", "mid", "冒一次险 / 赌一把",
     "你要说这次值得试试,哪怕没把握。",
     ("I'd rather take a chance.", "He took a chance and it paid off."),
     ("try the luck", "catch a chance")),
    ("coll-have-a-say", "have a say in", "E", "high", "有发言权 / 说得上话",
     "你要说这件事他也该有份决定。",
     ("Everyone should have a say in this.", "I had no say in it."),
     ("have the right to speak", "own a voice in")),
    ("coll-bear-in-mind", "bear in mind", "E", "mid", "记在心里 / 考虑进去",
     "你要提醒对方别忘了一个前提。",
     ("Bear in mind that it's a holiday.", "Worth bearing in mind."),
     ("keep in heart", "remember in mind")),
    ("coll-fix-a-problem", "fix a problem", "F", "core", "修好 / 解决掉",
     "你要说那个毛病已经修好了。",
     ("They fixed the problem.", "It's not an easy problem to fix."),
     ("repair the problem", "cure the problem")),
    ("coll-avoid-mistake", "avoid a mistake", "F", "mid", "避免出错",
     "你要说提前检查能少出岔子。",
     ("That avoids a lot of mistakes.", "It's a mistake worth avoiding."),
     ("escape the mistake", "prevent mistake happen")),
    ("coll-face-problem", "face a problem", "F", "mid", "直面问题",
     "你要说逃避没用,得正视。",
     ("We have to face the problem.", "They're facing serious problems."),
     ("meet the problem face", "front the problem")),
    ("coll-set-goal", "set a goal", "G", "core", "定一个目标",
     "你要说给自己定个明确的小目标。",
     ("Set yourself a realistic goal.", "We set a goal of ten a day."),
     ("make a goal", "build a goal")),
    ("coll-gain-experience", "gain experience", "G", "mid", "积累经验",
     "你要说这段工作让你学到不少。",
     ("I gained a lot of experience there.", "It's a good way to gain experience."),
     ("get experiences", "accumulate experience up")),
    ("coll-do-your-best", "do one's best", "G", "core", "尽力而为",
     "你要说你已经尽了全力。",
     ("I did my best.", "Just do your best."),
     ("try one's best effort", "make one's best")),
    ("coll-put-on-weight", "put on weight", "H", "mid", "长胖",
     "你要说最近胖了一点。",
     ("I've put on a bit of weight.", "He put on weight over winter."),
     ("add weight up", "grow fat")),
)

#: 动作词。中文往往一个字覆盖一大片("拿""撞""弄"),英文则分得很细,
#: 所以这一类的错误几乎全是**用一个过于笼统的动词去顶**。
_RAW_ACTIONS: tuple[tuple, ...] = (
    # ── I 手上的动作 ──────────────────────────────────────────────────────────
    ("act-push-door", "push a door open", "I", "core", "把门推开",
     "门没锁,你让对方直接推进去。",
     ("Just push the door open.", "He pushed the door open with his shoulder."),
     ("open the door by pushing force", "press the door open")),
    ("act-pull-drawer", "pull out a drawer", "I", "core", "把抽屉拉出来",
     "你要让人把抽屉拉开找东西。",
     ("Pull out the top drawer.", "The drawer won't pull out."),
     ("draw the drawer out", "pull the drawer come out")),
    ("act-press-button", "press a button", "I", "core", "按按钮",
     "你要让人按一下那个按钮。",
     ("Press the green button.", "Just press it twice."),
     ("push down the button", "hit the button")),
    ("act-flip-switch", "flip a switch", "I", "mid", "啪地拨动开关",
     "你要说顺手把开关拨了一下。",
     ("He flipped the switch on his way out.", "Flip it the other way."),
     ("turn the switch body", "move the switch")),
    ("act-twist-cap", "twist off a cap", "I", "mid", "把瓶盖拧开",
     "瓶盖很紧,你要说拧不动。",
     ("I can't twist the cap off.", "Twist it off and pour it in."),
     ("turn the bottle cover", "rotate off the cap")),
    ("act-squeeze-toothpaste", "squeeze the toothpaste", "I", "core", "挤牙膏",
     "你要说牙膏快挤不出来了。",
     ("Squeeze the toothpaste from the bottom.", "There's barely any left to squeeze out."),
     ("press the toothpaste", "push out the toothpaste")),
    ("act-pour-water", "pour water", "I", "core", "倒水",
     "你要给对方倒杯水。",
     ("Let me pour you some water.", "He poured it into a glass."),
     ("fall the water in", "put the water out")),
    ("act-spill", "spill a drink", "I", "core", "把饮料洒了",
     "你不小心把杯子碰倒,弄洒了。",
     ("I spilled coffee on my shirt.", "Careful, you'll spill it."),
     ("drop the drink out", "flow out the drink")),
    ("act-wring-towel", "wring out a towel", "I", "high", "把毛巾拧干",
     "毛巾湿透了,你要把水拧出来。",
     ("Wring it out before you hang it up.", "She wrung the towel out."),
     ("twist the towel dry", "squeeze dry the towel")),
    ("act-tear-open", "tear open a packet", "I", "mid", "把包装撕开",
     "你要把小包装袋撕开。",
     ("Tear it open at the top.", "He tore the packet open with his teeth."),
     ("break open the packet", "split the packet")),
    ("act-peel-apple", "peel an apple", "I", "core", "削苹果皮",
     "你要把苹果皮去掉再吃。",
     ("Do you want me to peel it?", "She peeled the apple for him."),
     ("cut the apple skin", "remove the apple skin")),
    ("act-chop-vegetables", "chop vegetables", "I", "core", "切菜(切成块)",
     "你在厨房把菜切好。",
     ("I'll chop the vegetables.", "Chop it finely."),
     ("cut the vegetable into pieces", "break the vegetables")),
    ("act-fold-paper", "fold a piece of paper", "I", "core", "把纸折起来",
     "你要把纸对折放进信封。",
     ("Fold it in half.", "He folded the letter and put it away."),
     ("bend the paper", "turn the paper over half")),
    ("act-roll-sleeves", "roll up your sleeves", "I", "mid", "把袖子卷起来",
     "你要动手干活,先把袖子卷上去。",
     ("He rolled up his sleeves and got to work.", "Roll your sleeves up."),
     ("turn up the sleeve", "fold the sleeves")),
    ("act-tie-shoelaces", "tie your shoelaces", "I", "core", "系鞋带",
     "你提醒对方鞋带开了。",
     ("Your shoelaces are undone — tie them.", "He stopped to tie his laces."),
     ("knot the shoe rope", "bind the shoelace")),
    ("act-zip-up", "zip up a jacket", "I", "core", "把外套拉链拉上",
     "外面冷,你让孩子把拉链拉上。",
     ("Zip your jacket up, it's freezing.", "The zip won't do up."),
     ("pull the zipper up", "close the zipper")),
    ("act-fasten-seatbelt", "fasten your seat belt", "I", "mid", "系安全带",
     "车要开了,你提醒对方系好。",
     ("Fasten your seat belt.", "Everyone buckled up."),
     ("tie the safety belt", "bind the seat belt")),
    ("act-plug-in", "plug something in", "I", "core", "插上插头 / 接上电源",
     "你要说手机忘了插电。",
     ("Did you plug it in?", "Plug the lamp in over there."),
     ("insert the plug", "connect the electricity line")),
    ("act-unplug", "unplug something", "I", "core", "拔掉插头",
     "你要让人把电器断电。",
     ("Unplug it before you clean it.", "I unplugged the router."),
     ("pull out the electricity", "take off the plug")),
    ("act-turn-off-tap", "turn off the tap", "I", "core", "关水龙头",
     "水还在流,你让人关掉。",
     ("Turn the tap off.", "The tap's dripping."),
     ("close the tap", "shut the water pipe")),
    ("act-wipe-table", "wipe the table", "I", "core", "擦桌子",
     "吃完饭你要把桌面擦一下。",
     ("Can you wipe the table?", "She wiped it down with a cloth."),
     ("rub the table clean", "brush the table")),
    ("act-sweep-floor", "sweep the floor", "I", "core", "扫地",
     "地上有碎屑,你要扫一扫。",
     ("I'll sweep the floor.", "He swept up the broken glass."),
     ("clean the floor by broom", "brush the ground")),
    ("act-mop-floor", "mop the floor", "I", "core", "拖地",
     "你要用拖把把地拖了。",
     ("The floor needs mopping.", "I just mopped — watch your step."),
     ("drag the floor", "wash the floor with stick")),
    ("act-scrub-pan", "scrub a pan", "I", "mid", "用力刷锅",
     "锅底糊了,要使劲刷。",
     ("You'll have to scrub it.", "He scrubbed the pan clean."),
     ("wash the pan hardly", "brush the pan strongly")),
    ("act-strike-match", "strike a match", "I", "high", "划火柴",
     "你要点蜡烛,先划根火柴。",
     ("He struck a match and lit the candle.", "The match wouldn't strike."),
     ("scratch a match", "rub a match fire")),
    ("act-stuff-into", "stuff something into", "I", "mid", "硬塞进去",
     "东西太多,你把它硬塞进包里。",
     ("He stuffed it into his pocket.", "Don't stuff it in like that."),
     ("push into forcefully", "press something inside")),
    ("act-hang-up-coat", "hang up a coat", "I", "core", "把外套挂起来",
     "进门后你让客人把外套挂上。",
     ("Hang your coat up over there.", "She hung it up by the door."),
     ("put the coat on hanger", "catch the coat up")),
    ("act-put-lid-on", "put the lid on", "I", "core", "盖上盖子",
     "你提醒对方把盖子盖好。",
     ("Put the lid on properly.", "The lid won't go on."),
     ("cover the lid", "close the cap above")),
    ("act-lift-box", "lift a box", "I", "core", "把箱子抬起来",
     "箱子很重,你要说抬不动。",
     ("It's too heavy to lift.", "Lift with your legs, not your back."),
     ("raise up the box", "move the box up")),
    ("act-carry-bag", "carry a bag", "I", "core", "拎着 / 提着包",
     "你要帮对方拿行李。",
     ("Let me carry that for you.", "She was carrying two bags."),
     ("take the bag on hand", "hold the bag walk")),

    # ── J 碰撞与身体 ──────────────────────────────────────────────────────────
    ("act-bump-into", "bump into someone", "J", "core", "撞到人(也指偶遇)",
     "你在路上不小心撞了别人一下。",
     ("Sorry, I bumped into you.", "I bumped into an old friend yesterday."),
     ("hit a person accidentally", "crash a person")),
    ("act-knock-over", "knock something over", "J", "core", "把东西碰倒",
     "你手一挥把杯子扫倒了。",
     ("I knocked the glass over.", "The cat knocked it over."),
     ("hit something down", "push something fall")),
    ("act-crash-into", "crash into", "J", "mid", "(车等)猛撞上去",
     "你要说车撞上了护栏。",
     ("The car crashed into a wall.", "He crashed into the back of a van."),
     ("hit heavily into", "collide the wall")),
    ("act-knock-on-door", "knock on the door", "J", "core", "敲门",
     "你到了门口要敲门。",
     ("Knock before you come in.", "Someone's knocking on the door."),
     ("hit the door", "beat the door")),
    ("act-tap-shoulder", "tap someone on the shoulder", "J", "mid", "拍一下肩膀",
     "你从背后轻拍对方引起注意。",
     ("She tapped me on the shoulder.", "He tapped the glass gently."),
     ("hit the shoulder lightly", "pat the shoulder to call")),
    ("act-poke", "poke someone", "J", "mid", "用手指戳一下",
     "你要说他用手指戳了你一下。",
     ("He poked me in the ribs.", "Stop poking me."),
     ("stab someone with finger", "point someone's body")),
    ("act-prick-finger", "prick your finger", "J", "high", "手指被扎破",
     "你被针尖扎了一下手指。",
     ("I pricked my finger on a thorn.", "She pricked herself with a needle."),
     ("stab the finger", "puncture the finger")),
    ("act-burst-balloon", "burst a balloon", "J", "mid", "把气球弄破",
     "气球被扎破了。",
     ("The balloon burst.", "He burst it with a pin."),
     ("stab the balloon broken", "explode the balloon")),
    ("act-slam-door", "slam a door", "J", "mid", "摔门 / 用力关门",
     "他生气地把门摔上。",
     ("He slammed the door behind him.", "Don't slam it."),
     ("close the door heavily", "beat the door shut")),
    ("act-smash", "smash something", "J", "mid", "摔碎 / 砸碎",
     "杯子掉地上碎了一地。",
     ("The vase smashed on the floor.", "He smashed the window."),
     ("break into pieces hardly", "fall and broken")),
    ("act-trip-over", "trip over something", "J", "mid", "被绊了一下",
     "你被地上的线绊到差点摔倒。",
     ("I tripped over the cable.", "Careful, you'll trip over it."),
     ("stumble by something", "fall by the cable")),
    ("act-slip", "slip on something", "J", "core", "脚下打滑",
     "地上有水,你差点滑倒。",
     ("I slipped on the wet floor.", "He slipped and fell."),
     ("slide and fall down", "glide on the floor")),
    ("act-shake-hands", "shake hands", "J", "core", "握手",
     "初次见面你要和对方握个手。",
     ("We shook hands and sat down.", "He shook my hand firmly."),
     ("hold hands", "catch hands together")),
    ("act-wave", "wave at someone", "J", "core", "朝某人招手",
     "你在远处朝朋友招手。",
     ("She waved at me from across the street.", "He waved goodbye."),
     ("shake hand to say hello", "swing hands at someone")),
    ("act-nod", "nod your head", "J", "core", "点头",
     "你点头表示同意。",
     ("He nodded and said nothing.", "She nodded in agreement."),
     ("move the head down", "shake the head yes")),
    ("act-shrug", "shrug your shoulders", "J", "mid", "耸肩(表示不知道或无所谓)",
     "你要说他只是耸了耸肩。",
     ("He just shrugged.", "She shrugged her shoulders."),
     ("raise the shoulders", "move shoulder up")),
    ("act-blink", "blink", "J", "mid", "眨眼",
     "你要说他盯着看,眼都不眨。",
     ("He didn't even blink.", "She blinked a few times."),
     ("close eyes quickly", "move the eyelid")),
    ("act-stamp-foot", "stamp your foot", "J", "high", "跺脚",
     "小孩闹脾气跺了一下脚。",
     ("The child stamped his foot.", "She stamped her feet to keep warm."),
     ("hit the ground with foot", "step the floor hardly")),
    ("act-rub-hands", "rub your hands", "J", "mid", "搓手",
     "天冷你搓手取暖。",
     ("He rubbed his hands together.", "She rubbed her eyes."),
     ("scratch the hands", "wipe the hands together")),
    ("act-pinch", "pinch someone", "J", "mid", "掐一下",
     "你要说被掐了一下胳膊。",
     ("She pinched my arm.", "He pinched himself to make sure."),
     ("press someone with fingers", "grip someone's skin")),
    ("act-kick-ball", "kick a ball", "J", "core", "踢球",
     "你要说他把球踢进了院子。",
     ("He kicked the ball over the fence.", "Kick it back to me."),
     ("play the ball with foot", "hit the ball by foot")),
    ("act-grab", "grab something", "J", "core", "一把抓住 / 顺手拿",
     "你要说他一把抓住了扶手。",
     ("He grabbed the handrail.", "Grab your coat and let's go."),
     ("catch something quickly", "hold something fast")),
    ("act-pick-up", "pick something up", "J", "core", "把东西捡起来 / 拿起来",
     "东西掉地上了,你要让人捡起来。",
     ("Pick it up, please.", "She picked up the phone."),
     ("take up something from floor", "lift something by hand")),
    ("act-drop", "drop something", "J", "core", "失手掉落",
     "你要说手一滑把手机摔了。",
     ("I dropped my phone.", "Don't drop it!"),
     ("let something fall down", "lose something on floor")),
    ("act-throw-away", "throw something away", "J", "core", "扔掉",
     "你要说那个盒子扔了吧。",
     ("Just throw it away.", "Don't throw that away — I need it."),
     ("throw something out of hand", "cast something away")),
)
