"""中级与高级句型——在基础 100 条之上再加两档。

分级标准不是词汇难度,是**语用难度**:

* 中级,会让人听出你不是在背课本:``It's not like …``、``I might as well …``、
  ``Mind you``。结构还是日常的,但拐弯和分寸多了一层。
* 高级,是母语者用来控场和收口的那些说法:``Be that as it may``、
  ``I'd be lying if I said …``、``No sooner had I … than …``。倒装、虚拟、
  以及"把话说死又留余地"的分寸都在这一档。

分组沿用基础那 8 个交际功能,这样整份清单始终按"我现在想干什么"检索。
中文情境提示里不出现任何英文——提示一旦泄题,产出练习就退化成朗读。
"""

from __future__ import annotations

_RAW_MID: tuple[tuple, ...] = (
    # ── A 缓和与委婉 ──────────────────────────────────────────────────────────
    ("mid-rather-not-get-into", "I'd rather not get into it.", "A", "我不太想细说",
     "别人追问一件你不愿展开的事,你要礼貌地挡回去。",
     ("I'd rather not get into it right now.",
      "It's a long story — I'd rather not get into it.")),
    ("mid-cant-be-bothered", "I can't be bothered to …", "A", "懒得去……(嫌麻烦)",
     "有件事你完全提不起劲去做,嫌麻烦。",
     ("I can't be bothered to cook tonight.",
      "He couldn't be bothered to reply.")),
    ("mid-might-as-well", "I might as well …", "A", "不如就……吧(反正也那样了)",
     "反正已经这样了,不如顺手把另一件事做了。",
     ("We're already here, so we might as well stay.",
      "I might as well walk — the bus takes just as long.")),
    ("mid-no-point", "There's no point in …", "A", "……没什么意义",
     "你要劝对方别白费力气。",
     ("There's no point in arguing about it.",
      "There's no point in waiting any longer.")),
    ("mid-hate-to", "I'd hate to …", "A", "我很不愿意……(委婉地提出顾虑)",
     "你担心某个不好的结果,想先说出来。",
     ("I'd hate to waste your time.",
      "I'd hate for you to find out later.")),
    ("mid-bear-with-me", "Bear with me.", "A", "容我一下(我正在理思路或处理)",
     "你需要对方多等几秒钟。",
     ("Bear with me, I'm almost done.",
      "Bear with me a second while I find it.")),

    # ── B 观点与立场 ──────────────────────────────────────────────────────────
    ("mid-inclined-to", "I'm inclined to …", "B", "我倾向于……(有偏向但不绝对)",
     "你心里有倾向,但还愿意被说服。",
     ("I'm inclined to say yes.",
      "I'm inclined to agree with her.")),
    ("mid-beginning-to-think", "I'm beginning to think …", "B", "我开始觉得……(想法在转变)",
     "一个你原先不信的念头,现在越来越成立。",
     ("I'm beginning to think we made a mistake.",
      "I'm beginning to think he was right.")),
    ("mid-last-thing", "The last thing I want is …", "B", "我最不想要的就是……",
     "你要强调某个结果你绝对想避免。",
     ("The last thing I want is to make it worse.",
      "The last thing we need is another meeting.")),
    ("mid-debatable", "That's debatable.", "B", "这个有待商榷(委婉的不同意)",
     "对方把一件其实有争议的事说成了定论。",
     ("That's debatable, to be honest.",
      "Whether it's cheaper is debatable.")),
    ("mid-not-necessarily", "Not necessarily.", "B", "不一定(否定对方的必然推论)",
     "对方从一件事直接推出了结论,但未必成立。",
     ("Not necessarily — it depends on the day.",
      "That's not necessarily true.")),
    ("mid-one-way-to-put-it", "That's one way to put it.", "B", "可以这么说吧(略带保留)",
     "对方的措辞你不完全赞同,但不想直接反驳。",
     ("That's one way to put it, I suppose.",
      "Well, that's one way of looking at it.")),

    # ── C 解释与澄清 ──────────────────────────────────────────────────────────
    ("mid-not-like", "It's not like …", "C", "又不是说……(反驳一个隐含的假设)",
     "对方的话里藏着一个不成立的前提,你要点破。",
     ("It's not like we had a choice.",
      "It's not like I did it on purpose.")),
    ("mid-thats-where", "That's where … comes in.", "C", "这就该……上场了",
     "前面讲完问题,现在引出解决它的那个东西。",
     ("That's where the backup plan comes in.",
      "That's where you come in.")),
    ("mid-matter-of", "It's a matter of …", "C", "这是……的问题(把焦点收窄)",
     "你要指出事情的性质到底属于哪一类。",
     ("It's just a matter of time.",
      "It's a matter of priorities, not money.")),
    ("mid-beside-the-point", "That's beside the point.", "C", "这不是重点",
     "对方说的虽然没错,但偏离了正在讨论的事。",
     ("That's beside the point — we still need an answer.",
      "Whether it's fair is beside the point.")),
    ("mid-to-put-it-mildly", "…, to put it mildly.", "C", "说得客气点……(其实更严重)",
     "实际情况比你说出口的还要糟,你要留个余味。",
     ("It didn't go well, to put it mildly.",
      "He wasn't happy, to put it mildly.")),
    ("mid-to-say-the-least", "…, to say the least.", "C", "这还是轻的",
     "你刚用了一个明显偏轻的词来形容一件大事。",
     ("It was awkward, to say the least.",
      "That's surprising, to say the least.")),
    ("mid-take-it-that", "I take it (that) …", "C", "我理解是……吧?(确认推测)",
     "你根据对方的反应推测了一件事,想确认一下。",
     ("I take it you've already heard.",
      "I take it that's a no?")),

    # ── D 叙述与经历 ──────────────────────────────────────────────────────────
    ("mid-as-it-happens", "As it happens, …", "D", "碰巧/其实正好……",
     "对方提到的事,你正好有关联或正好知道。",
     ("As it happens, I was there too.",
      "As it happens, I've got one right here.")),
    ("mid-slipped-my-mind", "It slipped my mind.", "D", "我给忘了(不是故意的)",
     "你忘了一件答应过的事,要道歉但说明不是有意的。",
     ("Sorry, it completely slipped my mind.",
      "It must have slipped his mind.")),
    ("mid-train-of-thought", "I lost my train of thought.", "D", "我忘了刚才要说什么",
     "被打断之后你的思路断了。",
     ("Sorry, I lost my train of thought.",
      "Where was I? I've lost my train of thought.")),
    ("mid-drawing-a-blank", "I'm drawing a blank.", "D", "我脑子一片空白(想不起来)",
     "你努力回忆某个名字,但完全想不起来。",
     ("I'm drawing a blank on her name.",
      "Ask me tomorrow — I'm drawing a blank.")),
    ("mid-struck-me", "It struck me that …", "D", "我忽然意识到……",
     "某个念头在某一刻突然冒出来。",
     ("It struck me that we'd never actually met.",
      "It suddenly struck me how long it had been.")),
    ("mid-no-wonder", "No wonder …", "D", "难怪……(找到原因了)",
     "刚知道的信息解释了之前的疑惑。",
     ("No wonder you're tired.",
      "No wonder it didn't work.")),

    # ── E 转折与让步 ──────────────────────────────────────────────────────────
    ("mid-granted", "Granted, …", "E", "诚然/就算是吧(先退一步)",
     "你要先承认对方一个站得住的点,再接着说。",
     ("Granted, it's not perfect, but it works.",
      "Granted, he did warn us.")),
    ("mid-mind-you", "Mind you, …", "E", "不过话说回来/提醒一句",
     "你刚说完一件事,要补一个会改变印象的细节。",
     ("It's cheap. Mind you, you get what you pay for.",
      "Mind you, she never actually promised anything.")),
    ("mid-ill-give-you-that", "I'll give you that.", "E", "这点我认(局部让步)",
     "大方向你不同意,但对方某一点确实说中了。",
     ("It was faster — I'll give you that.",
      "Fine, I'll give you that one.")),
    ("mid-youve-got-a-point", "You've got a point there.", "E", "你这话有道理",
     "对方一句话让你改变了一点看法。",
     ("You've got a point there, actually.",
      "He's got a point.")),
    ("mid-not-to-mention", "…, not to mention …", "E", "更别说……(再加一条理由)",
     "理由已经够多了,你还要追加一个。",
     ("It's expensive, not to mention slow.",
      "The noise, not to mention the smell.")),
    ("mid-let-alone", "…, let alone …", "E", "更不用说……(连前者都做不到)",
     "连简单的那件都办不到,更大的就别提了。",
     ("I can't afford a taxi, let alone a car.",
      "He can't cook pasta, let alone a whole meal.")),
    ("mid-far-from-it", "Far from it.", "E", "恰恰相反",
     "对方的判断不只是不准,而是完全反了。",
     ("Easy? Far from it.",
      "Far from it — it took months.")),
    ("mid-youd-think-but", "You'd think …, but …", "E", "你会以为……,结果……",
     "常理推出来的结论和现实不一样。",
     ("You'd think it'd be faster, but it isn't.",
      "You'd think they'd have called by now.")),

    # ── F 条件与推测 ──────────────────────────────────────────────────────────
    ("mid-thats-assuming", "That's assuming …", "F", "这还得假设……(指出前提不牢)",
     "对方的计划依赖一个未必成立的前提。",
     ("That's assuming everyone shows up.",
      "That's assuming nothing goes wrong.")),
    ("mid-odds-are", "Odds are …", "F", "十有八九……",
     "你要给一个相当有把握的推测。",
     ("Odds are they're stuck in traffic.",
      "Odds are it'll be fine.")),
    ("mid-chances-are-slim", "The chances of … are slim.", "F", "……的希望不大",
     "你要委婉地说某件事基本没戏。",
     ("The chances of getting a refund are slim.",
      "Chances of that happening are pretty slim.")),
    ("mid-id-be-surprised", "I'd be surprised if …", "F", "要是……我才意外(其实就是不信)",
     "你觉得某事几乎不可能,但说得含蓄。",
     ("I'd be surprised if he remembered.",
      "I'd be surprised if it lasts a year.")),
    ("mid-wouldnt-put-it-past", "I wouldn't put it past …", "F", "……干得出这种事",
     "某人做出一件出格的事,你一点也不意外。",
     ("I wouldn't put it past him.",
      "I wouldn't put it past them to cancel last minute.")),
    ("mid-just-as-well", "It's just as well …", "F", "幸好……(没发生反而是好事)",
     "原本的计划落空了,但结果反而更好。",
     ("It's just as well we didn't go.",
      "It's just as well — I was too tired anyway.")),
    ("mid-what-with", "What with … and …, …", "F", "又是……又是……,所以",
     "好几件事叠在一起,导致了某个结果。",
     ("What with the rain and the traffic, we were late.",
      "What with work and the kids, I never get a minute.")),
    ("mid-if-anything-goes-wrong", "If anything goes wrong, …", "F", "万一出问题的话……",
     "你要事先约定出状况时怎么办。",
     ("If anything goes wrong, just call me.",
      "If anything comes up, let me know.")),

    # ── G 互动与回应 ──────────────────────────────────────────────────────────
    ("mid-hear-me-out", "Hear me out.", "G", "先听我说完(别急着反对)",
     "对方刚听个开头就要打断你。",
     ("Just hear me out before you say no.",
      "Hear me out — it's not as crazy as it sounds.")),
    ("mid-not-get-ahead", "Let's not get ahead of ourselves.", "G", "先别想太远",
     "大家已经在讨论还没影的后续了。",
     ("Let's not get ahead of ourselves — nothing's signed yet.",
      "Don't get ahead of yourself.")),
    ("mid-take-your-word", "I'll take your word for it.", "G", "那我就信你了",
     "你没法亲自验证,选择相信对方。",
     ("I haven't tried it, but I'll take your word for it.",
      "I'll take your word for it this time.")),
    ("mid-beats-me", "It beats me why …", "G", "我真搞不懂为什么……",
     "一件事完全不合逻辑,你想不通。",
     ("It beats me why they changed it.",
      "Beats me.")),
    ("mid-on-second-thought", "On second thought, …", "G", "再想想还是……",
     "你刚说完一个决定,立刻改主意。",
     ("On second thought, let's just stay in.",
      "On second thought, maybe you're right.")),

    # ── H 话语组织 ────────────────────────────────────────────────────────────
    ("mid-now-that-you-mention", "Now that you mention it, …", "H", "经你这么一说……",
     "对方的话让你注意到一件之前没留意的事。",
     ("Now that you mention it, I did hear something.",
      "Now that you mention it, it has been a while.")),
    ("mid-come-to-think-of-it", "Come to think of it, …", "H", "仔细想想……",
     "说着说着你自己想起一个相关的细节。",
     ("Come to think of it, I've still got his keys.",
      "Come to think of it, that explains a lot.")),
    ("mid-all-things-considered", "All things considered, …", "H", "综合来看……",
     "把各方面因素放一起之后给一个总评。",
     ("All things considered, it went pretty well.",
      "All things considered, we were lucky.")),
    ("mid-in-hindsight", "In hindsight, …", "H", "事后回头看……",
     "当时没看出来,现在才明白。",
     ("In hindsight, I should have asked first.",
      "In hindsight, it was obvious.")),
)


_RAW_HIGH: tuple[tuple, ...] = (
    # ── A 缓和与委婉 ──────────────────────────────────────────────────────────
    ("high-be-lying", "I'd be lying if I said …", "A", "我要说……那是骗人的(委婉承认)",
     "你要承认一件不太想承认的实话,先给自己垫一句。",
     ("I'd be lying if I said I wasn't nervous.",
      "I'd be lying if I said it didn't bother me.")),
    ("high-much-as", "Much as I'd like to, …", "A", "虽然我很想,但……(委婉拒绝)",
     "你要拒绝一个你其实有兴趣的邀请。",
     ("Much as I'd like to, I can't make it.",
      "Much as I'd like to help, I'm tied up all week.")),
    ("high-with-all-due-respect", "With all due respect, …", "A", "恕我直言(接下来是不客气的话)",
     "你要在正式场合反驳一位比你资深的人。",
     ("With all due respect, that's not what the numbers show.",
      "With all due respect, I disagree.")),
    ("high-to-put-it-bluntly", "To put it bluntly, …", "A", "直说吧……(不再修饰)",
     "绕弯子没用了,你要把难听的话说出口。",
     ("To put it bluntly, it isn't working.",
      "To put it bluntly, we can't afford him.")),
    ("high-not-that-im-aware", "Not that I'm aware of.", "A", "据我所知没有(不把话说死)",
     "对方问有没有某件事,你认为没有但不敢打包票。",
     ("Has anything changed? Not that I'm aware of.",
      "Not that I'm aware of, but let me check.")),
    ("high-leave-it-at-that", "I'll leave it at that.", "A", "我就说到这儿(点到为止)",
     "再说下去就不合适了,你要主动收住。",
     ("I've said my piece — I'll leave it at that.",
      "Let's leave it at that for now.")),

    # ── B 观点与立场 ──────────────────────────────────────────────────────────
    ("high-not-so-much", "It's not so much … as …", "B", "与其说……不如说……",
     "对方的定性不太准,你要换一个更贴切的说法。",
     ("It's not so much the cost as the hassle.",
      "He's not so much angry as disappointed.")),
    ("high-go-so-far", "I'd go so far as to say …", "B", "我甚至敢说……(把话说重)",
     "你要给出一个比刚才更强的判断。",
     ("I'd go so far as to say it's the best they've done.",
      "I'd go so far as to call it reckless.")),
    ("high-wouldnt-go-that-far", "I wouldn't go that far.", "B", "倒也没到那个地步",
     "对方的评价过头了,你要往回拉一点。",
     ("A disaster? I wouldn't go that far.",
      "I wouldn't go that far, but it wasn't great.")),
    ("high-cant-help-but", "I can't help but feel …", "B", "我总觉得……(挥之不去的感觉)",
     "有个感觉你压不下去,尽管说不出确凿理由。",
     ("I can't help but feel we're missing something.",
      "I can't help but think it was deliberate.")),
    ("high-something-to-be-said", "There's something to be said for …", "B", "……自有它的道理",
     "一个看似平庸的做法,其实有它的好处。",
     ("There's something to be said for keeping it simple.",
      "There's a lot to be said for doing nothing.")),
    ("high-cuts-both-ways", "It cuts both ways.", "B", "这是双刃剑/两边都适用",
     "对方拿来支持自己的理由,其实对他自己也成立。",
     ("That argument cuts both ways.",
      "Flexibility cuts both ways.")),
    ("high-cant-have-both", "You can't have it both ways.", "B", "鱼和熊掌不可兼得",
     "对方同时要两个互相矛盾的东西。",
     ("You can't have it both ways — pick one.",
      "They want speed and quality; you can't have it both ways.")),

    # ── C 解释与澄清 ──────────────────────────────────────────────────────────
    ("high-precisely-the-point", "That's precisely the point.", "C", "这正是重点(对方无意中说中了)",
     "对方举的反例恰好证明了你的论点。",
     ("That's precisely the point I was making.",
      "Exactly — that's precisely the point.")),
    ("high-suffice-it-to-say", "Suffice it to say, …", "C", "只能说……(细节不便展开)",
     "完整经过不方便讲,你只给一个结论。",
     ("Suffice it to say, we won't be working with them again.",
      "Suffice it to say, it was a long night.")),
    ("high-needless-to-say", "Needless to say, …", "C", "不用说……(显而易见的结果)",
     "接下来的结果任何人都猜得到。",
     ("Needless to say, nobody was pleased.",
      "Needless to say, we missed the deadline.")),
    ("high-goes-without-saying", "It goes without saying that …", "C", "不言而喻……",
     "一件理所当然的事,你还是要正式说一句。",
     ("It goes without saying that safety comes first.",
      "It goes without saying, but thank you.")),
    ("high-fine-line", "There's a fine line between … and …", "C", "……和……只有一线之隔",
     "两个概念表面相近,但越界就变味了。",
     ("There's a fine line between confident and arrogant.",
      "It's a fine line between persistent and annoying.")),
    ("high-no-getting-around", "There's no getting around it.", "C", "这事躲不掉",
     "一个不想面对但绕不开的事实。",
     ("There's no getting around the cost.",
      "There's no getting around it — we have to start over.")),

    # ── D 叙述与经历 ──────────────────────────────────────────────────────────
    ("high-little-did-i-know", "Little did I know …", "D", "我当时完全没想到……(倒装)",
     "讲故事时预告一个当初没预料到的转折。",
     ("Little did I know it would take all year.",
      "Little did we know that was the last time.")),
    ("high-no-sooner", "No sooner had I … than …", "D", "我刚……就……(倒装)",
     "一件事刚做完,另一件立刻发生。",
     ("No sooner had I sat down than the phone rang.",
      "No sooner had we arrived than it started raining.")),
    ("high-had-i-known", "Had I known …, I'd have …", "D", "早知道……我就……(虚拟倒装)",
     "你为一个当初不知情而做错的决定表示遗憾。",
     ("Had I known, I'd have said something.",
      "Had I known it was that far, I'd have driven.")),
    ("high-were-it-not-for", "Were it not for …, …", "D", "要不是因为……(虚拟倒装)",
     "某个因素改变了整件事的走向。",
     ("Were it not for her, we'd still be stuck.",
      "Were it not for the weather, it'd have been perfect.")),
    ("high-as-it-turned-out", "As it turned out, …", "D", "后来证明……",
     "事后看来,当初的判断对或错。",
     ("As it turned out, he was right.",
      "As it turned out, nobody noticed.")),
    ("high-by-all-accounts", "By all accounts, …", "D", "大家都说……(转述公论)",
     "你没亲历,但听到的说法都一致。",
     ("By all accounts, it went well.",
      "By all accounts, she's excellent at it.")),
    ("high-not-for-lack-of-trying", "…, and not for lack of trying.", "D", "不是没努力过",
     "事情没成,但你要说明不是因为懈怠。",
     ("We didn't get it, and not for lack of trying.",
      "He never learned, though not for lack of trying.")),

    # ── E 转折与让步 ──────────────────────────────────────────────────────────
    ("high-be-that-as-it-may", "Be that as it may, …", "E", "话虽如此(正式的让步转折)",
     "对方说的都成立,但你的结论不变。",
     ("Be that as it may, we still have to deliver.",
      "Be that as it may, it's not our call.")),
    ("high-stand-corrected", "I stand corrected.", "E", "是我说错了(大方认错)",
     "对方拿出证据证明你弄错了。",
     ("You're right — I stand corrected.",
      "I stand corrected, thanks for checking.")),
    ("high-agree-to-disagree", "Let's agree to disagree.", "E", "我们各自保留意见吧",
     "争不出结果,你要体面地收场。",
     ("We'll agree to disagree on that one.",
      "Let's just agree to disagree and move on.")),
    ("high-all-the-more-reason", "All the more reason to …", "E", "那更应该……(把反对理由反过来用)",
     "对方拿某个困难当理由反对,你用它来支持自己。",
     ("All the more reason to start early.",
      "All the more reason to ask them directly.")),
    ("high-if-nothing-else", "If nothing else, …", "E", "退一万步说,至少……",
     "整件事不算成功,但至少有一个收获。",
     ("If nothing else, we learned what not to do.",
      "If nothing else, it was good practice.")),
    ("high-thats-pushing-it", "That's pushing it.", "E", "这就有点过了",
     "对方的要求或说法超出了合理范围。",
     ("Two days? That's pushing it.",
      "Calling it a bargain is pushing it.")),
    ("high-only-so-much", "There's only so much … can do.", "E", "……能做的也就这么多",
     "你要说明某个办法有天然的上限。",
     ("There's only so much I can do from here.",
      "There's only so much money can fix.")),

    # ── F 条件与推测 ──────────────────────────────────────────────────────────
    ("high-remains-to-be-seen", "That remains to be seen.", "F", "这还不好说(保留判断)",
     "对方已经下了结论,你觉得为时过早。",
     ("Whether it works remains to be seen.",
      "That remains to be seen, honestly.")),
    ("high-believe-it-when", "I'll believe it when I see it.", "F", "我看到了才信(表示怀疑)",
     "对方转述了一个你不太信的承诺。",
     ("They promised Friday? I'll believe it when I see it.",
      "I'll believe it when I see it in writing.")),
    ("high-anyones-guess", "It's anyone's guess.", "F", "谁也说不准",
     "结果完全无法预测。",
     ("How long it'll take is anyone's guess.",
      "Your guess is as good as mine.")),
    ("high-for-all-i-know", "For all I know, …", "F", "说不定……(我其实并不清楚)",
     "你要承认自己信息不足,什么情况都有可能。",
     ("For all I know, they've already left.",
      "For all I know, it was never sent.")),
    ("high-push-comes-to-shove", "If push comes to shove, …", "F", "真到了万不得已……",
     "你要给出最坏情况下的备选方案。",
     ("If push comes to shove, we can do it ourselves.",
      "If push comes to shove, I'll drive.")),
    ("high-barring", "Barring any surprises, …", "F", "不出意外的话……",
     "你要给一个有保留的承诺。",
     ("Barring any surprises, we'll be done by noon.",
      "Barring something unexpected, I'll be there.")),
    ("high-way-things-are-going", "The way things are going, …", "F", "照这个势头下去……",
     "按当前趋势外推一个结果。",
     ("The way things are going, we'll run out by June.",
      "The way things are going, nobody will be left.")),
    ("high-only-time-will-tell", "Only time will tell.", "F", "时间会证明",
     "现在无法判断对错,只能等。",
     ("Whether it was the right call, only time will tell.",
      "Only time will tell if it pays off.")),

    # ── G 互动与回应 ──────────────────────────────────────────────────────────
    ("high-touch-and-go", "It's touch and go.", "G", "还很悬(结果难料)",
     "一件事处在成败边缘。",
     ("It was touch and go for a while.",
      "It's still touch and go whether we'll make it.")),
    ("high-give-or-take", "…, give or take.", "G", "上下浮动/左右(给一个约数)",
     "你给一个大概的数字,留一点误差。",
     ("About twenty minutes, give or take.",
      "Ten years, give or take a couple.")),
    ("high-more-often-than-not", "More often than not, …", "G", "多半情况下……",
     "你要描述一个大概率但不绝对的规律。",
     ("More often than not, it sorts itself out.",
      "More often than not, they're late.")),
    ("high-high-time", "It's high time …", "G", "早就该……了(带点不耐烦)",
     "一件拖了很久的事,该做了。",
     ("It's high time we talked about this.",
      "It's high time someone said it.")),
    ("high-sooner-the-better", "The sooner …, the better.", "G", "越早……越好",
     "你要催促对方尽快动手。",
     ("The sooner we start, the better.",
      "The sooner this is over, the better.")),

    # ── H 话语组织 ────────────────────────────────────────────────────────────
    ("high-when-all-is-said", "When all is said and done, …", "H", "说到底……(最终的结论)",
     "讨论到最后,你要给一句定论。",
     ("When all is said and done, it's their decision.",
      "When all is said and done, we did our best.")),
    ("high-at-the-end-of-the-day", "At the end of the day, …", "H", "归根结底……",
     "你要把一堆细节归结到一个核心。",
     ("At the end of the day, it's about trust.",
      "At the end of the day, somebody has to pay for it.")),
    ("high-in-no-particular-order", "…, in no particular order.", "H", "排名不分先后",
     "你要列举几项,但不想让人读出轻重。",
     ("Three reasons, in no particular order.",
      "Here they are, in no particular order.")),
    ("high-for-the-record", "For the record, …", "H", "我把话说清楚……(正式声明)",
     "你要留一句明确的表态,免得日后被误解。",
     ("For the record, I never agreed to that.",
      "For the record, this was not my idea.")),
)
