"""母语者每天真的会脱口而出的整句。

和句型、搭配并列的第三条线,区别是**它不需要你填任何东西**:
整句是现成的,听到相应的场景就能原样甩出去。句型要接自己的内容,搭配要
嵌进句子里,只有这一类是"拿来即用"。

现有清单里本来就有 48 条属于这一类——凡是不含省略号的,就是完整的一句话。
它们按同一个规则自动归到这条线,id 不变,练习进度照旧。这个文件只放补充的。

选的都是对话里真实高频、而且中文母语者通常想不到的回应。很多是"反应性"的:
别人说完,你需要立刻接一句——这种时刻最没时间翻译,也最需要现成的。
"""

from __future__ import annotations

#: (id, 整句, 分组, 难度, 释义, 情境, 例句)
_RAW_ONELINERS: tuple[tuple, ...] = (
    # ── G 互动与回应 ──────────────────────────────────────────────────────────
    ("one-fair-enough", "Fair enough.", "G", "core", "行吧,可以理解(接受对方给的理由)",
     "对方说今晚太累不出门了,你表示理解。",
     ("\"I'm staying in tonight — I'm exhausted.\" \"Fair enough.\"",
      "Fair enough, let's do it your way.")),
    ("one-sounds-good", "Sounds good to me.", "G", "core", "我觉得可以(同意对方的提议)",
     "对方提议七点见,你没意见。",
     ("\"Shall we meet around seven?\" \"Sounds good to me.\"",
      "Friday works — sounds good.")),
    ("one-works-for-me", "Works for me.", "G", "core", "我这边没问题",
     "对方定了一个时间,你确认可以。",
     ("\"How about Thursday?\" \"Works for me.\"",
      "Either day works for me.")),
    ("one-tell-me-about-it", "Tell me about it.", "G", "mid", "可不是嘛(强烈同感,不是真让对方说)",
     "对方抱怨一件你也深受其苦的事。",
     ("\"These meetings never end.\" \"Tell me about it.\"",
      "\"Rent is insane here.\" \"Tell me about it.\"")),
    ("one-makes-two-of-us", "That makes two of us.", "G", "mid", "我也一样(我也有同样的处境)",
     "对方说他也没搞懂,你表示彼此彼此。",
     ("\"I have no idea what's going on.\" \"That makes two of us.\"",
      "\"I'm shattered.\" \"Makes two of us.\"")),
    ("one-im-all-ears", "I'm all ears.", "G", "mid", "你说,我听着呢",
     "对方说有件事想跟你讲,你示意他说。",
     ("\"Got a minute? I need your advice.\" \"Sure, I'm all ears.\"",
      "Go on, I'm all ears.")),
    ("one-say-no-more", "Say no more.", "G", "high", "懂了,不用多说",
     "对方刚起个头你就明白了,还很乐意配合。",
     ("\"If you're free Saturday…\" \"Say no more, I'm there.\"",
      "Say no more — consider it done.")),
    ("one-im-on-it", "I'm on it.", "G", "core", "我这就去办",
     "被交代一件事,你立刻应下。",
     ("\"Can you check the numbers?\" \"I'm on it.\"",
      "Already on it.")),
    ("one-leave-it-with-me", "Leave it with me.", "G", "mid", "交给我吧",
     "对方为一件事发愁,你接过来。",
     ("\"I still need to book the room.\" \"Leave it with me.\"",
      "Leave it with me, I'll sort it out.")),
    ("one-no-rush", "No rush.", "G", "core", "不着急,慢慢来",
     "你请人帮忙,但不想给对方压力。",
     ("Whenever you get a chance — no rush.",
      "\"Sorry, I haven't read it yet.\" \"No rush.\"")),
    ("one-take-your-time", "Take your time.", "G", "core", "慢慢来,别赶",
     "对方在手忙脚乱地找东西,你让他别急。",
     ("Take your time, we're early.",
      "\"Give me two minutes.\" \"Take your time.\"")),
    ("one-no-pressure", "No pressure.", "G", "mid", "别有压力(邀请或请求之后补一句)",
     "你发出邀请,又怕对方觉得非去不可。",
     ("Come if you want — no pressure.",
      "Think about it. No pressure either way.")),
    ("one-i-owe-you-one", "I owe you one.", "G", "mid", "欠你个人情",
     "别人帮了你一个不小的忙。",
     ("Thanks for covering for me — I owe you one.",
      "You've saved me. I owe you one.")),
    ("one-sorry-to-bother", "Sorry to bother you.", "G", "core", "不好意思打扰一下",
     "你要打断别人问个问题。",
     ("Sorry to bother you, do you have a second?",
      "Sorry to bother you again.")),
    ("one-im-good", "I'm good.", "G", "core", "我不用了 / 我没事(婉拒)",
     "别人问你还要不要再来一杯。",
     ("\"Another coffee?\" \"I'm good, thanks.\"",
      "\"Need a hand?\" \"I'm good.\"")),
    ("one-never-mind", "Never mind.", "G", "core", "算了,当我没说",
     "你问的事对方没听清,你决定不追了。",
     ("Never mind, it's not important.",
      "\"Sorry, what?\" \"Never mind.\"")),
    ("one-thatll-do", "That'll do.", "G", "mid", "这样就行了,够了",
     "东西不完美但已经够用,你喊停。",
     ("That'll do, let's move on.",
      "It's not perfect, but it'll do.")),
    ("one-ill-let-you-know", "I'll let you know.", "G", "core", "我回头告诉你",
     "你现在答不了,但会给个回话。",
     ("I'm not sure yet — I'll let you know.",
      "I'll let you know by Friday.")),
    ("one-suit-yourself", "Suit yourself.", "G", "mid", "随你便(略带无所谓)",
     "你劝了对方,他不听,你不再坚持。",
     ("\"I'll walk, it's fine.\" \"Suit yourself.\"",
      "Suit yourself, but don't say I didn't warn you.")),
    ("one-here-we-go-again", "Here we go again.", "G", "mid", "又来了(同样的事又发生)",
     "一件反复出现的烦人事再次上演。",
     ("The printer's broken. Here we go again.",
      "\"He's late.\" \"Here we go again.\"")),

    # ── B 观点与立场 ──────────────────────────────────────────────────────────
    ("one-good-shout", "That's a good shout.", "B", "mid", "这主意不错(偏英式)",
     "对方提了个你没想到的好办法。",
     ("\"Why don't we book in advance?\" \"That's a good shout.\"",
      "Good shout — let's do that.")),
    ("one-im-up-for-that", "I'm up for that.", "B", "core", "我愿意 / 算我一个",
     "朋友约你晚上出去,你很乐意。",
     ("\"Fancy going for a drink later?\" \"I'm up for that.\"",
      "I'd be up for that.")),
    ("one-ill-pass", "I'll pass.", "B", "mid", "我就不了(婉拒)",
     "有人邀你参加,你不想去但不想解释太多。",
     ("\"Karaoke after dinner?\" \"I'll pass, thanks.\"",
      "I think I'll pass on this one.")),
    ("one-count-me-out", "Count me out.", "B", "mid", "别算我 / 我不参加",
     "你明确表示不加入这件事。",
     ("If it's that early, count me out.",
      "Count me out of the hiking bit.")),
    ("one-im-not-fussed", "I'm not fussed.", "B", "high", "我无所谓(偏英式)",
     "对方让你选,你是真的没偏好。",
     ("\"Tea or coffee?\" \"I'm not fussed.\"",
      "I'm not fussed either way.")),
    ("one-good-for-you", "Good for you.", "B", "core", "替你高兴 / 真不错",
     "对方分享了一件好消息。",
     ("\"I finally quit.\" \"Good for you!\"",
      "Good for you — that takes guts.")),
    ("one-better-you-than-me", "Better you than me.", "B", "high", "幸好不是我(半开玩笑)",
     "对方接了一个你绝不想碰的活。",
     ("\"I'm presenting on Monday.\" \"Better you than me.\"",
      "Rather you than me.")),
    ("one-cant-complain", "I can't complain.", "B", "core", "还不错,没什么好抱怨的",
     "别人问你最近过得怎么样。",
     ("\"How's life?\" \"Pretty good, can't complain.\"",
      "Busy, but I can't complain.")),

    # ── E 转折与让步 ──────────────────────────────────────────────────────────
    ("one-cant-argue-with-that", "Can't argue with that.", "E", "mid", "这我没法反驳",
     "对方说了一句你完全同意、也无话可说的话。",
     ("\"It's cheaper and faster.\" \"Can't argue with that.\"",
      "Well, I can't argue with that.")),
    ("one-point-taken", "Point taken.", "E", "mid", "我接受你的意见",
     "被批评得有道理,你大方认下。",
     ("\"You should've asked first.\" \"Point taken.\"",
      "Fair criticism — point taken.")),
    ("one-dont-get-me-wrong", "Don't get me wrong.", "E", "mid", "别误会我的意思",
     "你要先打个预防针,接下来的话容易被听岔。",
     ("Don't get me wrong, I like it — I just can't afford it.",
      "Don't get me wrong, he's great at his job.")),
    ("one-it-is-what-it-is", "It is what it is.", "E", "mid", "没办法,就这样吧(接受无法改变的事)",
     "事情已经成定局,抱怨也没用。",
     ("\"We missed the last train.\" \"Yeah… it is what it is.\"",
      "It's not ideal, but it is what it is.")),
    ("one-easier-said-than-done", "Easier said than done.", "E", "mid", "说起来容易做起来难",
     "对方给的建议听着简单,实际很难。",
     ("\"Just stop worrying.\" \"Easier said than done.\"",
      "Saving money is easier said than done.")),
    ("one-not-a-big-deal", "It's not a big deal.", "E", "core", "没什么大不了的",
     "对方为一件小事过意不去。",
     ("\"Sorry about that.\" \"It's not a big deal.\"",
      "Honestly, it's not a big deal.")),

    # ── F 条件与推测 ──────────────────────────────────────────────────────────
    ("one-you-never-know", "You never know.", "F", "core", "谁知道呢 / 说不定呢",
     "一件事没把握,但也不是没可能。",
     ("\"Maybe I'll end up working abroad again.\" \"You never know.\"",
      "Give it a try — you never know.")),
    ("one-worth-a-shot", "It's worth a shot.", "F", "mid", "值得一试",
     "成功率不高,但试试也不亏。",
     ("It might not work, but it's worth a shot.",
      "\"Should I just email them?\" \"Worth a shot.\"")),
    ("one-fingers-crossed", "Fingers crossed.", "F", "core", "但愿顺利",
     "结果还没出来,你表示祝愿。",
     ("Interview's tomorrow — fingers crossed.",
      "Fingers crossed it doesn't rain.")),
    ("one-whats-the-catch", "What's the catch?", "F", "high", "这里头有什么坑?",
     "条件好得不太真实,你起了疑心。",
     ("Free for a year? What's the catch?",
      "There's always a catch.")),
    ("one-play-it-by-ear", "Let's play it by ear.", "F", "high", "到时候再说 / 看情况随机应变",
     "你不想现在就把计划定死。",
     ("We'll play it by ear.",
      "Let's play it by ear and see how we feel.")),

    # ── A 缓和与委婉 ──────────────────────────────────────────────────────────
    ("one-ill-see-what-i-can-do", "I'll see what I can do.", "A", "mid", "我尽量(不打包票)",
     "被拜托一件你不能保证的事。",
     ("No promises, but I'll see what I can do.",
      "\"Any chance of an extension?\" \"I'll see what I can do.\"")),
    ("one-ill-give-it-a-go", "I'll give it a go.", "A", "core", "我试试看",
     "没做过的事,你愿意上手试一下。",
     ("I've never cooked it, but I'll give it a go.",
      "Give it a go — what's the worst that can happen?")),
    ("one-i-wouldnt-bother", "I wouldn't bother.", "A", "high", "我觉得不值当,别费那劲了",
     "你认为对方打算做的事没必要。",
     ("Honestly, I wouldn't bother.",
      "I wouldn't bother queuing — it's always full.")),
    ("one-thats-about-it", "That's about it.", "A", "mid", "差不多就这些了",
     "你讲完了,示意没有别的内容。",
     ("…and that's about it.",
      "\"Anything else?\" \"No, that's about it.\"")),
)
